### ISSUE TITLE
Detect and list a possible slug conflict with the referral variable setting

### ISSUE THREAD

**Issue by DrewAPicture** [AffiliateWP/AffiliateWP#2253] opened 2017-06-05 19:59 UTC
Ticket: https://secure.helpscout.net/conversation/374155391/60349/?folderId=205529

Just troubleshooted affiliate URLs not working on the homepage and causing weird redirects. The customer's referral var was "rewards" and visiting homepage/?rewards=7 redirected you to homepage/rewards/?rewards=7. All other sub-pages worked fine with pretty and non-pretty affiliate URLs.

After going around a couple of times checking plugin compatibility and other issues, I discovered an attachment that had a slug of "rewards". Editing the slug fixed the problem.

This conflict and redirect were seriously difficult to debug, and I only did the `get_page_by_path( 'rewards' )` search as a wild guess. So I think it would be useful to notate possible slug conflicts within the settings description if one exists so something like this could be avoided in the future.

**Comment by pippinsplugins** [comment] 2017-06-05 21:34
Duplicate of https://github.com/AffiliateWP/AffiliateWP/issues/1660 :)

**Closed** 2017-06-05 21:34 UTC
Labels: bug, duplicate
