### ISSUE TITLE
Shiny Updates-style add-on authentication and installation for add-ons

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/AffiliateWP#1337] opened 2016-06-04 02:51 UTC
It would be cool if AffiliateWP add-ons could be installed in a manner similar to the [Shiny Updates](https://make.wordpress.org/core/2016/06/02/proposal-more-shiny-updates/) proposal in WordPress 4.6.
- The free add-ons would (ideally) leverage WordPress internals for shiny updates.
- We may need to introduce some manner of auth (yay) for Pro add-ons to authenticate the site/license (perhaps similar to how it's implemented in Gravity Forms).
- Here's a fictional but _tantalizing_ mockup:

![mockup of shiny updates in AffiliateWP](https://cldup.com/FVZzuqCx7R.gif)

**Comment by ramiabraham** [comment] 2016-06-04 02:53
_Unrelated: I just noticed this is issue #1337_ 🎉

**Comment by pippinsplugins** [comment] 2016-06-04 02:55
Related: https://github.com/AffiliateWP/AffiliateWP/issues/1261

**Comment by michaelbeil** [comment] 2016-06-04 05:43
That GIF makes me want to see this released now.

**Comment by pippinsplugins** [comment] 2016-11-29 18:28
Closing as a duplicate of #1261

**Closed by pippinsplugins** 2016-11-29 18:28 UTC
Labels: enhancement
