### ISSUE TITLE
Rejected referrals to be updated to Unpaid if associated order is completed

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/AffiliateWP#1752] opened 2016-10-25 21:47 UTC
If a referral gets marked as Rejected due to a failed order and then the customer comes back and successfully completes the order, the referral remains Rejected, instead of changing to Unpaid.

I don't think this is right. The referral should change to `Unpaid`, but only so long as the current status is `Pending` or `Rejected`. A `Paid` referral should remain unchanged.

**Comment by pippinsplugins** [comment] 2016-10-25 21:50
@sumobi could you test this please?

**Comment by DrewAPicture** [comment] 2016-10-25 22:13
PR looks good.

**Comment by sumobi** [comment] 2016-10-25 22:45
@pippinsplugins What's the best way to test this with EDD? 

I tested with EDD and Stripe payment gateway, using a declined credit card number to simulate a declined card, but EDD doesn't create the order initially, unless it's successful.

I then tried a normal Stripe payment to create the order, then set it to "revoked" from the payment history (affwp setting is enabled to revoke referral), but that didn't reject the referral. As per the code I can see that the referral is only revoked when refunded, or the payment is deleted entirely (but then I can't approve it again)

So then I ran a test payment and refunded the order which rejected the referral. I was thinking I could then "complete" the payment and the rejected referral would move to "unpaid" again (as per this PR) but that didn't happen.

Side discussion, I think we haven't accounted for some scenarios when a payment is manually modified from the admin, where the referral should be rejected, i.e revoking a payment in EDD, setting it to "failed", "abandoned", "cancelled" etc.

**Comment by pippinsplugins** [comment] 2016-10-26 00:07
WooCommerce would be the easiest. It's the only integration I'm currently aware of where this happens.

1. Setup PayPal standard gateway
2. Go to checkout
3. Submit and go to PayPal
4. Click cancel on PayPal
5. Return to checkout and change payment method to something else
6. Complete order

Referral should end up as `Unpaid`.

**Comment by davefx** [comment] 2016-10-26 07:44
I think that the actual problem is that we are actually marking a referral as rejected when its corresponding WooCommerce order gets into 'failed' status. 
An WooCommerce in a failed status is not a revoked nor a refunded order, so I think that the problem is generated because we are rejecting something that shouldn't be rejected at the first place. I think this referrals should remain in 'pending' status.

**Comment by michaelbeil** [comment] 2016-10-26 15:39
Hmm, that is an interesting thought to remove that action @davefx.

Perhaps we can merge both PRs as a part of this. Well, after further thought, the above PR from Pippin should account for the WC order fail.

We should also address @sumobi's comment further:

> I think we haven't accounted for some scenarios when a payment is manually modified from the admin, where the referral should be rejected, i.e revoking a payment in EDD, setting it to "failed", "abandoned", "cancelled" etc. 

If a failed or abandoned payment is then picked up again and a payment is completed, the referral should be set to a status of Unpaid, in my opinion. I believe that is what this issue is pertaining to.

@AffiliateWP/core thoughts?

**Comment by pippinsplugins** [comment] 2016-10-26 18:04
I don't agree that a failed payment shouldn't mark a referral as rejected, but I do think it should only mark it as rejected if the current status is `Unpaid`. Going from `Pending` to `Rejected` is kind of silly as the referral was never accepted to begin with.

**Comment by michaelbeil** [comment] 2016-10-26 18:24
Then we should probably remove the following per #1757:

```php
add_action( 'woocommerce_order_status_pending_to_failed', array( $this, 'revoke_referral_on_refund' ), 10 );
```

**Comment by sumobi** [comment] 2016-10-27 01:31
@pippinsplugins Tested twice with WooCommerce. The pending referral goes to rejected, but I'm sad to say that it does not go from rejected to unpaid. Instead, a new pending referral is created.

![screen shot 2016-10-27 at 2 30 37 pm](https://cloud.githubusercontent.com/assets/52581/19750937/f5cc47fc-9c51-11e6-8562-ddd6b2616161.png)

**Comment by davefx** [comment] 2016-10-27 03:59
@sumobi Which patch did you test? The one from @pippinsplugins or the one from me?
With my patch it shouldn't go to rejected status...

**Comment by davefx** [comment] 2016-10-27 04:05
@pippinsplugins Currently, the `revoke_referral_on_refund` function checks if the setting "Should unpaid referrals get automatically rejected when the originating purchase is refunded or revoked?" is active.
A failed payment is not a refunded nor revoked purchase.

**Comment by sumobi** [comment] 2016-10-27 04:48
@davefx I've only yet tested the one from @pippinsplugins

**Comment by pippinsplugins** [comment] 2016-10-27 15:41
Do you see the same behavior on `master`?

**Comment by DrewAPicture** [comment] 2016-11-11 00:44
Looks like this needs some further massaging. Punting to 1.9.6.

**Comment by pippinsplugins** [comment] 2017-05-31 15:12
@sumobi @DrewAPicture could you guys give this another try now for me on `issue/1752`?

**Comment by sumobi** [comment] 2017-06-01 04:39
@pippinsplugins When cancelling the order from PayPal the referral stayed at `pending`. Going through checkout again and arriving at PayPal created a brand new `pending` referral. Completing the purchase didn't set the referral to `unpaid`.

**Comment by pippinsplugins** [comment] 2017-06-26 19:50
There are two things here that need addressed:

1. The original bug
2. A bug introduced by the fix for the original bug

To replicate the original bug:

1. Visit your Woo store from a referral link
2. Add a product to the cart
3. Checkout
4. Submit checkout and go to PayPal (enable PayPal if you haven't)
5. You will now have a pending referral.
6. From PayPal.com, click the back button.
7. Go to Affiliates > Referrals and reject the pending referral that was created
8. Return to checkout and submit checkout but use Stripe (ping @amdrew if you need API keys)
9. The rejected referral is supposed to be changed from Rejected to Unpaid but it is not.

@DrewAPicture To replicate @amdrew's bug report in the fix:

1. Visit your Woo store from a referral link
2. Add a product to the cart
3. Checkout
4. Submit checkout and go to PayPal (enable PayPal if you haven't)
5. You will now have a pending referral
6. From PayPal.com, click the back button
7. Now submit checkout but use Stripe (ping @amdrew if you need API keys)
8. You will now have a _second_ referral that is marked as Unpaid. It was supposed to update the previous Pending referral to Unpaid instead of creating a new one.

**Comment by DrewAPicture** [comment] 2017-06-26 23:20
@pippinsplugins So, in my testing on `issue/1752`, I followed all of the steps and still only ended up with one referral marked as unpaid. I'm a little confused about a couple of things:

* Should I be testing for the bug for the fix?
* What's with the PayPal then Stripe thing?

**Comment by DrewAPicture** [comment] 2017-06-27 17:00
OK, so I just tested this again on `issue/1752` and got the same result (the first time I think i forgot the "Mark the pending referral rejected" step. This time I submitted the checkout and went to PayPal, marked the referral rejected, went back to checkout and completed it with Stripe. That converted the previously rejected referral to Unpaid.

I think we're good to go here.

**Comment by pippinsplugins** [comment] 2017-06-28 14:18
Merging then! If we encounter new edge cases or similar behaviors, we can open a new issue specific to that.

**Closed** 2017-06-28 14:19 UTC
Labels: enhancement
