### ISSUE TITLE
Shop page not shown in WooCommerce when using pretty affiliate URL

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#955] opened 2015-11-09 00:38 UTC
- AffiliateWP 1.7.8 
- Brand new sub-subsite install
- Latest version of WooCommerce
- Permalinks flushed and AffiliateWP settings saved
- Everything else default settings

When you visit the default WooCommerce shop page using a pretty affiliate URL (http://wc3.affwp.dev/shop/ref/1/), you see this:

![screen shot 2015-11-09 at 1 29 07 pm](https://cloud.githubusercontent.com/assets/52581/11023756/86aaa32c-86e6-11e5-82ec-9632a6da2bb3.png)

Visiting the shop without a pretty referral URL shows the shop (http://wc3.affwp.dev/shop/)
![screen shot 2015-11-09 at 1 35 34 pm](https://cloud.githubusercontent.com/assets/52581/11023770/c66e8794-86e6-11e5-8b3a-1bf6384646e8.png)

Non-pretty affiliate URLs don't have an issue.

@wordmaid can also replicate this issue

**Comment by pippinsplugins** [comment] 2015-11-09 15:21
I can't replicate this.

**Comment by pippinsplugins** [comment] 2015-11-09 15:22
I've tested both with the shop page set as the front page and a standard page.

**Comment by pippinsplugins** [comment] 2015-11-09 15:22
Scratch that, it happens now that I updated WooCommerce.

**Comment by pippinsplugins** [comment] 2015-11-09 15:24
Actually I get even stranger results.

Mine only shows 1 product but indicates there are two:
![screen shot 2015-11-09 at 9 23 57 am](https://cloud.githubusercontent.com/assets/1034109/11037492/9e7b30ca-86c3-11e5-8383-019ba7b3bd7f.png)

This happens to be with and without a referral variable.

**Comment by pippinsplugins** [comment] 2015-11-09 15:25
And now it works properly, both with a referral URL and with out. I went to Settings > General and clicked Save.

Does that fix it for you @sumobi and @wordmaid ?

**Comment by sumobi** [comment] 2015-11-10 00:02
@pippinsplugins won't budge for me :-1:

**Comment by wordmaid** [comment] 2015-11-10 00:15
@pippinsplugins me either :cry:

**Comment by pippinsplugins** [comment] 2015-11-10 21:56
@sumobi Can you test on our live test site? Does it happen to you there?

**Comment by michaelbeil** [comment] 2015-11-10 22:31
I do not see any issues on AWP 1.7.9, WP latest trunk, regular settings, and a subdirectory multisite.

**Comment by sumobi** [comment] 2015-11-11 00:28
@pippinsplugins works fine on dev site with referral URL.

![screen shot 2015-11-11 at 1 02 49 pm](https://cloud.githubusercontent.com/assets/52581/11080413/1d385216-8878-11e5-93b7-c59c0304819c.png)

**Comment by pippinsplugins** [comment] 2015-11-12 00:10
@sumobi Can you identify any differences between dev site and your local?

**Comment by sumobi** [comment] 2015-11-12 00:13
@pippinsplugins I'll do some more testing, see if I can pinpoint where the issue is coming from.

**Comment by pippinsplugins** [comment] 2015-11-20 18:55
@sumobi discover anything?

**Comment by sumobi** [comment] 2015-11-20 23:08
@pippinsplugins Haven't yet no. Feel free to bump.

**Comment by michaelbeil** [comment] 2016-03-26 00:36
Moving this over from 919.

I am seeing a similar issue with pretty permalinks even after saving AWP settings on AffiliateWP 1.7.16 and WooCommerce 2.5.5 except that it is showing up on the shop page with the following permalink settings: 
![screen shot 2016-03-25 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/4752949/14055616/537d130e-f2b1-11e5-989f-6b2c885c4138.png)

Permalink settings of a customer where affiliate links for category pages 404s (https://pivotstar.co.uk/products/athletic-tanks/ref/2; where `products` is the product category base):
![screen shot 2016-03-25 at 17 33 52](https://cloud.githubusercontent.com/assets/4752949/14055626/632d28d4-f2b1-11e5-8e8c-3345546fd757.png)

What I am seeing locally with the shop referral link with thte top permalink settings set: 
![screen capture on 2016-03-25 at 17-39-44](https://cloud.githubusercontent.com/assets/4752949/14055693/d82e1d64-f2b1-11e5-84d5-1049c3fdf7ef.gif)

However, when I travel to a product category affiliate link all works fine: 
![screen capture on 2016-03-25 at 17-43-20](https://cloud.githubusercontent.com/assets/4752949/14055724/296b33ce-f2b2-11e5-8be4-80490cb401a2.gif)

Single product page works fine: 
![screen capture on 2016-03-25 at 17-54-41](https://cloud.githubusercontent.com/assets/4752949/14055784/b27d5dfe-f2b2-11e5-9be6-7cdfe35c76ee.gif)

Note: non-pretty URLs work fine.

There is also a 404 on a /products/ page which is utilizing the archive-product.php template file.

General permalink setting for posts:
/blog/%postname%/

Product Permalink base:
/products/%product_cat%/

**Comment by pippinsplugins** [comment] 2016-03-28 18:53
This makes me sad.

**Comment by michaelbeil** [comment] 2016-03-28 18:55
As it does me.

**Comment by michaelbeil** [comment] 2016-04-13 22:02
https://github.com/AffiliateWP/AffiliateWP/commit/8137a2552661ad5e8b0467a11c5925e9ae02d662 seems to do the trick. I shall make a :cake: for @DrewAPicture.

**Comment by pippinsplugins** [comment] 2016-04-14 01:19
@sumobi could you confirm as well?

**Comment by DrewAPicture** [comment] 2016-04-14 19:52
Added a PR: #1197

**Comment by DrewAPicture** [comment] 2016-04-20 14:49
I think we'd just like to get a sign-off from @sumobi here before merging.

**Comment by pippinsplugins** [comment] 2016-04-20 15:06
:+1:

**Comment by sumobi** [comment] 2016-04-20 20:09
Will test soon

**Comment by sumobi** [comment] 2016-04-20 22:09
@pippinsplugins @DrewAPicture Can't flaw it, nice work. Merge away!

**Comment by DrewAPicture** [comment] 2016-04-20 22:17
Thanks @sumobi!

Merged #1197.

**Comment by pippinsplugins** [comment] 2016-04-20 23:27
Excellent!

**Comment by sumobi** [comment] 2017-05-15 23:36
Re-opening.

Customer is facing this issue with only WooCommerce 3.0.6 and AffiliateWP 2.0.8 active + the TwentySixteen theme: https://secure.helpscout.net/conversation/359912938/58643/?folderId=205527

I can also replicate locally, as can @wordmaid.
___
If `Product permalinks` is set to `/shop/` you see this:

![screen shot 2017-05-16 at 11 33 20 am](https://cloud.githubusercontent.com/assets/52581/26083752/98f00654-3a2b-11e7-880c-a519bc25d719.png)
___
If `Product permalinks` is set to `Default` you see this:
![screen shot 2017-05-16 at 11 33 35 am](https://cloud.githubusercontent.com/assets/52581/26083766/ada8adbc-3a2b-11e7-81a7-1067885858df.png)
___
My actual shop page with no pretty affiliate link:
![screen shot 2017-05-16 at 11 33 53 am](https://cloud.githubusercontent.com/assets/52581/26083771/ba68dc66-3a2b-11e7-8a98-a3f451747519.png)

**Comment by DrewAPicture** [comment] 2017-05-15 23:41
Sounds like something changed in WC to make `force_shop_page_for_referrals()` break.

**Comment by sumobi** [comment] 2017-05-15 23:42
So far I've tested back to v2.0.3 and it's still not working

**Comment by sumobi** [comment] 2017-05-15 23:47
It should also be noted that it _did_ work on the customer's site a day or 2 ago after @wordmaid logged in and flushed the permalinks and then re-saved the general tab of affwp's settings. However now it's not working after the referral variable was changed a few times between `rewards` and `ref`.

It didn't take me much to replicate locally however, but maybe it means something.

**Comment by sumobi** [comment] 2017-05-15 23:49
Ahh just found that switching back to WC 2.6.14 fixes it, so def a 3.0.X issue by the looks of it

**Comment by DrewAPicture** [comment] 2017-05-16 08:05
So basically the gist of the problem is that in 3.0+, WooCommerce generates hardcoded rewrites, including ones using the `shop` page base (based on whatever the URI is of the page). The reason the 404 is happening is that the affiliate ID is being parsed by WordPress as a page ID, thus the 404.

This is the offending rewrite: `[shop slug]/([^/]+)(?:/([0-9]+))?/?$`

I played around a little bit with registering a more verbose rewrite rule that incorporates the referral var, but haven't seen consistent results yet.

**Comment by DrewAPicture** [comment] 2017-05-16 08:06
See `wc_fix_rewrite_rules()` for where the rules are added.

**Comment by DrewAPicture** [comment] 2017-05-16 15:38
Added a PR that should address this: #2220

@AffiliateWP/core Please test!

**Comment by pippinsplugins** [comment] 2017-05-16 15:45
Replicated problem on `master` and confirmed the fix on `issue/955`. PR looks good.

**Comment by gspice** [comment] 2017-05-16 17:10
Had this happen on a site a few weeks ago, but thought it had to do with their specific setup.  They had to turn off pretty aff links to get rid of the 404s.  I will ask them if I can test it or if they have staging to test:

https://secure.helpscout.net/conversation/349314292/57350/?folderId=205529

**Comment by sumobi** [comment] 2017-05-16 18:58
@DrewAPicture Works for me! 👍

**Comment by wordmaid** [comment] 2017-05-16 19:17
@DrewAPicture Works for me too!

**Comment by pippinsplugins** [comment] 2017-05-16 19:35
Merging.

**Comment by sumobi** [comment] 2017-06-08 02:37
@DrewAPicture Sadly, this has popped up again.

Had a customer with this exact issue, running the latest versions of AffiliateWP and WooCommerce. I deactivated all plugins and switched themes and the issue still occurred with just the above 2 plugins. 

Visiting the permalinks page and saving the General tab of the AffWP settings had no effect. I also tried locally on two different computers but was unable to replicate the issue.

There is some good news however. I found a workaround which fixed it for the customer on both their live and staging sites.

@gspice @michaelbeil tagging you in case you see this in support.

What fixed it on the customer's sites:

1. On the `Settings -> Permalink` page, I changed the WooCommerce's "product permalinks" option  from `Default` to `Custom`. I then entered `/shop/` for the setting and saved.
2. I then changed it back to `Default` and saved again.
3. I then I saved the General tab of AffiliateWP's settings.

I don't know if it mattered that I entered a value for the custom field or not, but those were the exact steps I followed.

**Comment by DrewAPicture** [comment] 2017-06-08 13:53
I'm thinking the reason cycling the settings in this way works is that WooCommerce only sets `use_verbose_page_rules` – which we rely on for adding the rewrite rule – when a custom product base is enabled. They never disable it again, meaning that you have to cycle it once and then never again.

@sumobi What were their initial settings in terms of what was already in the Custom box (if anything)? If they had chosen the default, their product permalinks would've been /product/product-slug, so I'm a little confused about a shop page connection.

**Comment by sumobi** [comment] 2017-06-09 00:41
@DrewAPicture There was nothing in the `Custom base` field

**Comment by sumobi** [comment] 2017-06-12 23:56
@DrewAPicture Another instance of this. This time however I only needed to do steps 1 and 2 above.

**Comment by DrewAPicture** [comment] 2017-06-13 00:44
@sumobi OK, so I've submitted a new PR: #2277 to _always_ register the rewrite for the shop page regardless of permalink settings.

**Comment by pippinsplugins** [comment] 2017-06-14 19:15
@DrewAPicture let's make a new issue for tracking purposes and put this fix in 2.1.

**Comment by DrewAPicture** [comment] 2017-06-15 07:16
Created #2282. Re-closing.

**Closed by DrewAPicture** 2017-06-15 07:16 UTC
Labels: bug, Has PR, i:WooCommerce
