### ISSUE TITLE
payout_id defaults to 0, sometimes causing DB write errors on failure

### ISSUE THREAD

**Issue by nhadsall** [AffiliateWP/AffiliateWP#2230] opened 2017-05-20 15:06 UTC
WordPress database error Duplicate entry '0' for key 'PRIMARY' for query INSERT INTO mbm_affiliate_wp_payouts` (`payout_id`, `owner`, `status`, `date`, `affiliate_id`, `referrals`, `amount`, payout_method`) VALUES (0, 1, 'paid', '2017-05-20 15:03:59', 3247, '232', '10', 'manual') made by do_action('wp_ajax_process_batch_request'), WP_Hook->do_action, WP_Hook->apply_filters, affwp_process_batch_request, AffWP\Utils\Batch_Process\Export\CSV->process_step, AffWP\Utils\Batch_Process\Export\CSV->csv_rows_out, AffWP\Utils\Batch_Process\Generate_Payouts->get_data, affwp_add_payout, Affiliate_WP_Payouts_DB->add, Affiliate_WP_DB->insert

Was something changed in the code to write payout_id as 0 or did the table index change? We run payouts monthly, so not sure when this bug crept in.

**Comment by pippinsplugins** [comment] 2017-05-26 14:48
@nhadsall I have not seen any other reports of that. Did it happen just the one time?

**Comment by DrewAPicture** [comment] 2017-05-26 19:48
I'd also be curious to know if this is a one-time thing or recurring problem?

**Comment by nhadsall** [comment] 2017-06-07 23:28
This continues to happen and is also happening on a client's site.

**Comment by DrewAPicture** [comment] 2017-06-09 00:06
@nhadsall If you could please submit a [support request](https://affiliatewp.com/support/) support ticket it would be very helpful to try getting this identified and fixed.

Please outline the steps to reproduce the problem, any related error log entries, and include a copy of the site's System Info log (retrievable via Affiliates > Tools > System Log) it would be appreciated. GitHub isn't a terribly good avenue for support requests, especially for posting system info logs that you might not want to be publicly viewable :-)

Thanks.

**Comment by DrewAPicture** [comment] 2017-06-19 18:51
OK, I think I know what's happening here. I haven't been able to reproduce the problem locally, but I think the problem is that we're incorrectly defining a default value for the `payout_id` column (as 0) in `get_column_defaults()`. This may have just been overlooked when payout objects were introduced. What we want to be doing is supplying a default value for `affiliate_id` instead.

Case in point, for referrals, there's a default 0 for `affiliate_id`, for affiliates, `user_id`, for visits, `affiliate_id` and `referral_id`, but never the primary key of the table.

Setting the milestone for 2.1.

**Comment by DrewAPicture** [comment] 2017-06-19 19:05
PR (including two tests): #2286

**Comment by DrewAPicture** [comment] 2017-06-19 19:09
Actually, milestoning for 2.0.10. We've had enough reports of persistent issues that I think it warrants a point release.

**Comment by DrewAPicture** [comment] 2017-06-19 20:13
Sent a patched version @ `issue/2230` to this customer for confirmation: https://secure.helpscout.net/conversation/383456735/61349/

**Comment by DrewAPicture** [comment] 2017-06-19 20:17
@nhadsall If you'd like to help us test, there's a patched version you can install.

Steps to install the patched version of the plugin:

1. Ensure the **Remove Data on Uninstall** option is **not** checked in Affiliates > Settings > Misc. This will allow you to retain all of your data after deleting the plugin.
2. Deactivate and delete the AffiliateWP plugin running on your site
3. Download the patched version here: https://github.com/AffiliateWP/AffiliateWP/archive/issue/2230.zip
4. Upload and activate the patched version of the plugin

**Closed** 2017-06-19 21:23 UTC
Labels: bug, Has PR
