### ISSUE TITLE
Restrict Content Pro: purchases creating referrals that shouldn't 

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2085] opened 2017-03-08 22:49 UTC
This ticket has the history and admin account to log in:

https://secure.helpscout.net/conversation/326388477/54187/?folderId=1170842

Each membership subscription is creating a referral even though a discount code was not used.  They are not using affiliate links yet, only discount codes for their existing affiliates.  Currently any new purchase creates a referral for the affiliate id 27 (kc).  Previously it was another affiliate and they deleted it and it's now attached to this one.   

Also, the reference numbers in the Referral => Reference column do not link to anything.  They appear to attempt to link to Payments but the payment number is off by one.  Also searching the payments by any 3 digit payment id returns empty.  (not sure if that is a separate bug)

Referral created by user's test purchase this morning:

Member

https://bloomforwomen.com/wp-admin/admin.php?page=rcp-members&edit_member=6252

Invoice

https://bloomforwomen.com/wp-admin/index.php?payment_id=923&rcp-action=download_invoice&_wpnonce=77ab51e20f

Referral:

https://bloomforwomen.com/wp-admin/admin.php?page=affiliate-wp-referrals&referral_id=212&action=edit_referral

**Comment by DrewAPicture** [comment] 2017-03-09 00:35
Hmm. I logged in to the customer's site (in one browser) and double checked all settings and then switched over to sandbox mode so test Stripe CC would work.

Then in a second browser I registered two test members and neither generated referrals. So that's expected.

I can definitely see the referrals pointing to phantom payments in their admin though. I also noticed, for instance, that their settings are set to flat rate and $18 for recurring referrals, which seem to be the amount of the most recent referrals. Don't know if there's a connection there or not, but worth mentioning the correlation in case it's a clue.

Either way, @gspice what steps did you take _exactly_ to reproduce the problem?

**Comment by gspice** [comment] 2017-03-09 00:51
@DrewAPicture I did not do the test purchase from this morning , the customer did.  He purchased from the website page.  I was not sure how to go into test mode on Stripe to accomplish but I can revisit to see what I can find out.  Yes, you are correct, the rate for recurring referrals is $18 so it would seem these new purchases it believes are recurring payments?   

Regarding the reference payment id, in fairness, if you go to RCP's payment screen and type in a valid invoice number to search by it returns empty.  Not sure if that was searchable by the invoice number at one time, and is that a separate bug?

**Comment by pippinsplugins** [comment] 2017-03-10 02:29
@nosegraze could you lend a hand here?

**Comment by gspice** [comment] 2017-03-10 02:35
I asked the customer to try another test using a different browser completely (like Drew did in his two tests) and report back.  He responded:  

> I ran that test and it is still creating "rogue referrals." Again, remember that it's not only with new subscriptions but with any subscription transaction that takes place. New or existing it doesn't matter.

I wonder if it has to do with the connection to our payment processing service. We use Stripe. That would make sense that the test purchase in sandbox didn't create a referral. My thought is that it only happens when there's an actual transaction taking place in Stripe.

**Comment by DrewAPicture** [comment] 2017-03-10 03:32
For what it's worth, the transactions I tried using sandbox mode
intentionally didn't use any coupon codes or affiliate URLs as the customer
mentioned referrals were being created regardless.

So the lack of new referrals when there wasn't something to tie the
transactions to an affiliate was expected.

**Comment by nosegraze** [comment] 2017-03-10 12:47
Interesting things of note..

The references not linking to the payments seems to be because it's using the payment ID number as the reference. Though I looked through the AffiliateWP code and that seems to _supposed_ to be using the "subscription key" for the reference. The reference links don't link anywhere because you can't search by payment ID.

I looked at the last 5-10 payments in this person's site and none of them have subscription keys filled out in the member profiles. They're all blank.

**Comment by gspice** [comment] 2017-03-10 22:25
What should my next steps be with the user?  I will follow up with him after the weekend.

**Comment by pippinsplugins** [comment] 2017-03-12 21:42
This has to have something to do with Recurring Referrals; it uses the payment ID as the `reference`, whereas core uses the subscription key (32char key). 

Recurring Referrals does this:
```php
/**
 * Insert referrals on subscription payments
 *
 * @access  public
 * @since   1.0
*/
public function record_referral_on_payment( $payment_id, $args, $amount ) {

	$referral = affiliate_wp()->referrals->get_by( 'reference', $args['subscription_key'], $this->context );

	if( ! $referral || ! is_object( $referral ) || 'rejected' == $referral->status || 'pending' == $referral->status ) {
		return false; // This signup wasn't referred or is the very first payment of a referred subscription
	}

	$args = array(
		'reference'    => $payment_id,
		'affiliate_id' => $referral->affiliate_id,
		'description'  => $args['subscription'],
		'amount'       => $amount,
		'custom'       => $args['subscription_key']
	);

	$referral_id = $this->insert_referral( $args );

	$this->complete_referral( $referral_id );

}
```

That makes me think `$referral = affiliate_wp()->referrals->get_by( 'reference', $args['subscription_key'], $this->context );` is returning unexpected results for some reason.

Digging further.

**Comment by pippinsplugins** [comment] 2017-03-12 21:44
Looks like something is wiping out the subscription keys for members:
![screen shot 2017-03-12 at 4 43 29 pm](https://cloud.githubusercontent.com/assets/1034109/23836230/14942450-0743-11e7-96d6-42f705cbdb2f.png

**Comment by pippinsplugins** [comment] 2017-03-12 21:48
I think this is happening due to core not properly checking if the `$row_id` parameter is empty:
```php
/**
 * Retrieves a referral by a specific field.
 *
 * @access  public
 * @since   1.0
 *
 * @param string $column  Column name. See get_columns().
 * @param string $context Optional. Context for which to retrieve a referral. Default empty.
 * @return object|null Database query result object or null on failure.
*/
public function get_by( $column, $row_id, $context = '' ) {
	global $wpdb;

	$and = '';
	if( ! empty( $context ) ) {
		$and = " AND context = '" . esc_sql( $context ) . "'";
	}

	return $wpdb->get_row( $wpdb->prepare(  "SELECT * FROM $this->table_name WHERE $column = '%s'$and LIMIT 1;", $row_id ) );
}
```

@gspice I'm going to manually update the customer's site with a fix for this. Could you please have them keep an eye on it and let you know if the problem is resolved from this point on? If so, we'll get a real patch put in.

**Comment by pippinsplugins** [comment] 2017-03-12 21:49
Fix I put in:
```php
	/**
	 * Retrieves a referral by a specific field.
	 *
	 * @access  public
	 * @since   1.0
	 *
	 * @param string $column  Column name. See get_columns().
	 * @param string $context Optional. Context for which to retrieve a referral. Default empty.
	 * @return object|null Database query result object or null on failure.
	*/
	public function get_by( $column, $row_id, $context = '' ) {
		global $wpdb;

		if( empty( $column ) || empty( $row_id ) ) {
			return null;
		}

		$and = '';
		if( ! empty( $context ) ) {
			$and = " AND context = '" . esc_sql( $context ) . "'";
		}

		return $wpdb->get_row( $wpdb->prepare(  "SELECT * FROM $this->table_name WHERE $column = '%s'$and LIMIT 1;", $row_id ) );
	}
```

**Comment by gspice** [comment] 2017-03-13 16:34
@pippinsplugins  Awesome!  I've let the customer know the approx time you put the fix in, and to let us know if rogue referrals appear after that.

**Comment by pippinsplugins** [comment] 2017-03-13 18:57
PR submitted.

**Closed** 2017-03-23 17:06 UTC
Labels: bug, Has PR, needs testing, Unit Tests
