### ISSUE TITLE
On front-end Visits tab, Converted icons are not displaying

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#1947] opened 2017-01-23 16:33 UTC
The colors appear as before, but the checkmark and Xs are no longer displaying when viewing on the front-end /?tab=visits.  They do appear correctly in the WP admin area  under Affiliates -> Visits.  

Plugin verison: 1.9.8 

Reported on this ticket:
https://secure.helpscout.net/conversation/308757556/51502/?folderId=205524

![converted-checkboxes-problem](https://cloud.githubusercontent.com/assets/3018245/22212738/adff2d06-e146-11e6-9943-9c7869736c73.jpg)

**Comment by sumobi** [comment] 2017-01-23 18:56
@AffiliateWP/core I can't replicate this on v1.9.8, can anyone else?

**Comment by DrewAPicture** [comment] 2017-01-23 22:05
@sumobi Looks like the dashicons stylesheet isn't getting enqueued.

**Comment by sumobi** [comment] 2017-01-23 22:30
@DrewAPicture can you replicate the issue?

**Comment by DrewAPicture** [comment] 2017-01-27 21:26
@sumobi Haven't been able to replicate it either, was just pointing out that dashicons being dequeued is the likely culprit. Might be a conflict with another plugin dequeuing the dashicons stylesheet.

Works as expected in 2.0.

**Comment by sumobi** [comment] 2017-01-27 22:45
@DrewAPicture Yep, it certainly looks like it.

@gspice Was this an issue that you replicated locally or only on the customer's site? Trying to determine if this is actually an issue, or only affects the 1 customer.

**Comment by DrewAPicture** [comment] 2017-01-30 00:06
Punting to 2.0.2 since none of us have been able to reproduce.

**Comment by DrewAPicture** [comment] 2017-02-10 16:36
Still unable to reproduce. Closing.

**Comment by gspice** [comment] 2017-02-10 16:51
@DrewAPicture  I still get this in one of my test sites.  I will look to see if it's a theme issue.

**Comment by DrewAPicture** [comment] 2017-02-14 22:25
Added the WooCommerce tag even though this is more in the realm of plugin-compat. Moving to the 2.0.2 milestone.

**Comment by pippinsplugins** [comment] 2017-02-15 01:25
Does the issue only happen on WooCommerce sites?

**Comment by gspice** [comment] 2017-02-17 00:38
So far, it seems to be WooCommerce sites.

**Comment by gspice** [comment] 2017-02-27 05:47
Just happened to see this problem on Paul Jarvis's ChimpEssentials.com site....I am an affiliate there.  I couldn't not see evidence of WooCommerce but I'm not 100% sure on that:

![chimpessentials-affiliate-area](https://cloud.githubusercontent.com/assets/3018245/23350130/3114d3da-fc6d-11e6-9369-6031ed82240c.png)

**Comment by DrewAPicture** [comment] 2017-03-01 19:33
Unfortunately, it looks like the customer @gspice was working with has already in some way "fixed" this issue. This seems a lot like dashicons is either getting dequeued by something, or possibly replaced with something else using the dashicons handle (which would be _doing_it_wrong()).

I haven't been able to reproduce this locally running WooCommerce or anything else.

**Comment by gspice** [comment] 2017-03-01 19:42
Thanks @DrewAPicture.  Sorry to be the naggy ninny, but I'm wondering if this is computer-specific? Perhaps based on what fonts are installed?  The above screen shot still looks the same on Firebox, Chrome (after clearing cache) and on Safari I logged in, which I never use Safari, and it shows that column completely blank - I guess their choice for not showing the funky boxes.

**Comment by gspice** [comment] 2017-03-10 22:21
Another one, user from our MemberPress bug:

https://github.com/AffiliateWP/affiliate-wp-recurring-referrals/issues/59


![dashicons](https://cloud.githubusercontent.com/assets/3018245/23815374/c9bb12e2-059c-11e7-934c-918705d1739f.png)

**Comment by DrewAPicture** [comment] 2017-03-14 00:11
I'll bet this has to do with customers using custom templates for the visits tab, since we hard-coded the `dashicons` enqueue in dashboard-tab-visits.php starting around 2.0.

**Comment by DrewAPicture** [comment] 2017-03-14 00:13
Working up a patch for enqueuing `dashicons` if there is a copy of dashboard-tab-visits.php present in the active theme directory. Related: #2041

**Comment by gspice** [comment] 2017-03-14 00:19
FYI, I don't use a custom template and it's on my WooCommerce test site.  However, it is a theme that doesn't enqueue `dashicons`.

**Comment by DrewAPicture** [comment] 2017-03-14 01:59
It shouldn't matter whether the _theme_ enqueues `dashicons` since we're enqueueing it ourselves. I'll do some more testing, but I wouldn't be surprised if the custom template thing was one cause of the problem.

**Comment by sumobi** [comment] 2017-04-24 03:53
Ran into this on a customer's site while troubleshooting something different. Customer is using Divi with a Divi child theme activated but I tried replicating with their exact themes locally and the icons show correctly. No affwp related template files in use. The dashicons CSS file is definitely being stripped from the page's HTML. Tested with Firefox and Chrome.

**Comment by DrewAPicture** [comment] 2017-04-24 14:30
Added a PR that always enqueues dashicons on the visits tab. This differs from the previous approach of enqueuing it as a depedency of affwp-forms in that it uses `affwp_enqueue_style()` which provides the ability to short-circuit the enqueue.

Of course, this doesn't cover the case where another plugin or theme has reregistered the `dashicons` handle as something else or altogether deregistered it – which I suspect is a likely cause of this in some scenarios, but this should work for most situations.

**Comment by DrewAPicture** [comment] 2017-04-24 14:31
PR: #2184

**Comment by pippinsplugins** [comment] 2017-04-24 22:50
Looks good to me.

**Closed** 2017-04-24 22:50 UTC
Labels: bug, Has PR, i:WooCommerce

**Comment by gspice** [comment] 2017-04-25 20:23
Yay!  These icons have never displayed for me on my local Woo test site, but now they do with 2.0.7
![visits-dashicons](https://cloud.githubusercontent.com/assets/3018245/25406091/6ce1f72e-29ba-11e7-87c6-fe1ff15035cd.png)
