### ISSUE TITLE
Allow visits to be exported from Affiliates -> Visits section

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#837] opened 2015-09-12 13:31 UTC
It would be useful if admins could export their visits data (preferably to .CSV), should they want to see how many visits came from a particular landing page (and improve it/change it).

**Comment by pippinsplugins** [comment] 2015-09-12 18:49
Good idea.

How does everyone feel about adding options to export unique visits only? Or perhaps showing unique URLs only (one per row) and then including a count column for the number of times that URL was logged.

**Comment by wordmaid** [comment] 2015-09-22 05:19
@pippinsplugins: I think unique URLs with a count would be cool - that way if a bunch of traffic is coming from an affiliate's post (for example), the admin will see that affiliate is driving a lot of traffic their way. They can then cross-reference it with actual conversions, if they like.

It would be great, though, to also have every single visit available to view, as not all visits are converted. Admins may want to see which have converted/haven't converted, or how many were converted from a particular referring URL/affiliate.

I do think the more options we can give users in terms of Visits data, the better - then they can use what they need. So perhaps it would be most useful to include all visits, and then be able to filter by unique visits?

**Comment by pippinsplugins** [comment] 2015-09-22 13:54
I 100% agree. We should have advanced filtering capabilities so admins can view/export any set of visits they want.

**Comment by wordmaid** [comment] 2015-09-22 19:57
Absolutely agree! :+1:

**Comment by pippinsplugins** [comment] 2017-08-08 19:41
Duplicate of https://github.com/AffiliateWP/AffiliateWP/issues/2270

**Closed by pippinsplugins** 2017-08-08 19:41 UTC
Labels: enhancement
