### ISSUE TITLE
WooCommerce account registration does not work when the PayPal integration is enabled

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#1676] opened 2016-10-02 01:15 UTC
WooCommerce account registration from the "my account" page does not work when the PayPal integration is enabled.

To replicate (AffiliateWP v1.9.1):

1. Enable the PayPal integration

2. From the WooCommerce settings (/wp-admin/admin.php?page=wc-settings&tab=account) make sure `Enable registration on the "My Account" page` is enabled.

3. Visit the `/my-account` page on the front-end and try and register a new account. It will reload the page and nothing will happen. Try again without PayPal enabled and it will work fine.

The PayPal integration inserts code into the HTML of the page via the `scripts()` method. Is it possible to only load this perhaps on pages where paypal buttons are actually used?

**Comment by michaelbeil** [comment] 2016-10-02 02:20
Confirmed here too. It would definitely be best to only conditionally load the PayPal integration script on PayPal button pages.

**Comment by DrewAPicture** [comment] 2016-10-02 05:32
The problem is that PayPal buttons can be present on almost any page. The PayPal integration is different from most of the others in that it's global – it detects client-side click events on PayPal buttons on whichever page they happen to be present, vs something like WooCommerce which happens on the server-side when you go through a check out process. This behavior makes it both incredibly flexible and incredibly prone to wreaking havoc elsewhere.

All of that said, I think the way to go is to continue loading the script globally and simply exit the script if no PayPal elements are detected on the page.

**Comment by DrewAPicture** [comment] 2016-10-02 05:56
Added a PR: #1677

In this particular instance, the PayPal script exits early if the `<form>` action attribute value doesn't match what's expected. In the case of this WooCommerce form, there's no `action` attribute at all, which, actually causes the PayPal script to continue to running. The PR fixes this behavior.

**Comment by pippinsplugins** [comment] 2016-10-02 22:49
PR looks good, merged.

**Closed by pippinsplugins** 2016-10-02 22:49 UTC
Labels: bug, Has PR, i:PayPal, i:WooCommerce, needs testing
