### ISSUE TITLE
Upgrade database notice appears on fresh installs

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#2101] opened 2017-03-15 00:51 UTC
Installed AffiliateWP on a fresh sub-site of a MS installation and the upgrade database notice appears.

**Comment by DrewAPicture** [comment] 2017-03-15 17:54
Looks like some cruft from the merge into 2.0 was left over. `$this->version` was never actually assigned a value. Turns out 2.0 can't be less than `null`.

PR: #2102

**Comment by sumobi** [comment] 2017-04-20 01:18
This is still an issue. Just created a new sub-site and activated AffiliateWP 2.0.6:

<img width="1161" alt="screen shot 2017-04-20 at 1 17 35 pm" src="https://cloud.githubusercontent.com/assets/52581/25208910/cbacfc06-25cb-11e7-8e59-29ecd590a343.png">

**Comment by DrewAPicture** [comment] 2017-04-20 16:25
@sumobi Can you try installing a copy off of the `release/2.1` branch and confirm this is still happening?

**Comment by sumobi** [comment] 2017-04-21 00:33
@DrewAPicture Confirmed, still an issue with 2.1

**Comment by DrewAPicture** [comment] 2017-04-21 15:14
Does running the upgrade process clear the notice? This may just be a case of not setting the upgrade routine complete in newer versions.

**Comment by sumobi** [comment] 2017-04-21 22:42
After clicking upgrade database, you see:

![screen shot 2017-04-22 at 10 41 26 am](https://cloud.githubusercontent.com/assets/52581/25298379/5222b12c-2748-11e7-977b-ed71198e8181.png)

Clicking to dismiss the notice correctly removes it.

**Comment by pippinsplugins** [comment] 2017-05-30 19:56
@DrewAPicture if we could also include a tile that shows the average / total number of referrals in payouts, that would be swell.

**Comment by DrewAPicture** [comment] 2017-05-31 02:22
Simple PR: #2242 

@sumobi Could you please retest here?

**Comment by pippinsplugins** [comment] 2017-05-31 02:26
@DrewAPicture Logic looks good but there is a fatal error during install:

( ! ) Notice: Trying to get property of non-object in /app/public/wp-content/plugins/affiliate-wp/includes/misc-functions.php on line 993

**Comment by DrewAPicture** [comment] 2017-05-31 02:39
Oh yeah, it's cause we haven't loaded the upgrader at this point. I'll look into it.

**Comment by DrewAPicture** [comment] 2017-05-31 02:41
@pippinsplugins Try again after 2d27265e9fc25d68b509379fcb191ee680668886?

**Comment by pippinsplugins** [comment] 2017-05-31 02:43
Nope, still fatals.

**Comment by DrewAPicture** [comment] 2017-05-31 04:22
@pippinsplugins OK, give it another shot, please.

Moved toward setting the upgrades complete directly and skipping the Utils class – just making sure to load the multisite files in non-multisite for `get_sites()`, `switch_to_blog()` etc.

**Comment by sumobi** [comment] 2017-05-31 06:54
@DrewAPicture @pippinsplugins 
I'm not seeing the upgrade notice after the latest commit 👍

**Comment by DrewAPicture** [comment] 2017-05-31 14:26
Merged #2242.

**Comment by amdrew** [comment] 2017-06-29 23:06
I'm seeing the upgrade notice again after activating 2.0.10.1 on a sub-site of my MS installation:
![screen shot 2017-06-30 at 10 59 38 am](https://user-images.githubusercontent.com/52581/27714301-244b1fba-5d84-11e7-8208-70550bc5bcca.png)

**Comment by DrewAPicture** [comment] 2017-06-29 23:13
@amdrew This was only fixed against 2.1.

**Comment by amdrew** [comment] 2017-06-29 23:13
Ahh oops that's right

**Closed by DrewAPicture** 2017-06-29 23:13 UTC
Labels: bug
