### ISSUE TITLE
Options to disable each email 

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/AffiliateWP#1923] opened 2017-01-14 02:41 UTC
We should include checkboxes so a site admin can choose which email/s can be disabled. Currently, only _all_ emails can be disabled.

Related: https://github.com/AffiliateWP/AffiliateWP/issues/659

**Comment by ramiabraham** [comment] 2017-09-06 18:59
@AffiliateWP/core 

- [PR ready for review](https://github.com/AffiliateWP/AffiliateWP/pull/2373)
- Options to disable were added for the emails that have template content settings (_application accepted_, and _new referral_ were added, as well as the two that don't, _pending_ and _rejected_ registrations.

**Comment by pippinsplugins** [comment] 2017-09-07 19:16
@ramiabraham need one small change

**Comment by ramiabraham** [comment] 2017-09-07 20:00
@pippinsplugins Corrected!

**Comment by pippinsplugins** [comment] 2017-09-08 15:11
@ramiabraham Another small change request on the PR.

**Comment by ramiabraham** [comment] 2017-09-08 15:19
@pippinsplugins Updated in PR.

**Comment by pippinsplugins** [comment] 2017-09-11 20:10
Merged.

**Comment by gspice** [comment] 2018-04-27 01:02
Question: While testing I noticed the new /Emails settings no longer include the email subject and content sections for `Pending` and `Accepted` affiliate registrations.  Shouldn't we add these back before release?

**Comment by pippinsplugins** [comment] 2018-04-27 01:27
@gspice that was unintended, good catch!

**Comment by gspice** [comment] 2018-04-27 17:41
@pippinsplugins  Well, I'm embarrassed....there is no issue here. I didn't realize that the `Pending` and `Rejected` sections of the **Emails** tab are only visible if you have the **Require Approval** option checked under the **Misc** tab.   Pretty clever setup actually!   This works as designed on the beta.

**Comment by pippinsplugins** [comment] 2018-04-27 19:43
Oh . . . hehe, I missed it too :)

**Closed** 2018-05-04 00:59 UTC
Labels: Priority: High, enhancement
