### ISSUE TITLE
Improve Emails screen layout

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#948] opened 2015-11-05 07:51 UTC
From a UX perspective, it would be awesome to have an **Email Options** section at the top of the _Emails_ screen for the general email options, and then give each email its own section (in case additional features are added to each specific email in the future). Perhaps just a simple divider line like in the General tab could make look a lot cleaner and easier to read. What do you guys reckon?

**Comment by pippinsplugins** [comment] 2015-11-05 21:19
Big =1

**Comment by codelion7** [comment] 2016-01-09 21:36
Definitely

**Comment by pippinsplugins** [comment] 2016-01-11 16:16
I agree.

**Comment by gspice** [comment] 2017-02-23 16:58
Love this suggestion, was just coming to create issue for something similar - can we bring all email content to this main area?  Thinking of the ones sent via code.

**Comment by ramiabraham** [comment] 2017-09-07 19:56
@AffiliateWP/core Added a PR - https://github.com/AffiliateWP/AffiliateWP/pull/2378

**Comment by pippinsplugins** [comment] 2017-09-08 15:11
@ramiabraham I think the `Notify Admin` option should be in the `Registration Email Options` section instead of above it.

**Comment by ramiabraham** [comment] 2017-09-08 18:10
@pippinsplugins Updated in https://github.com/AffiliateWP/AffiliateWP/commit/3c1012b56cd83c2ed488b24c1611db67946091d3

**Comment by pippinsplugins** [comment] 2017-09-14 03:49
@ramiabraham looks like we have a merge conflict now. Could you update it please?

**Comment by ramiabraham** [comment] 2017-10-04 21:54
@pippinsplugins @amdrew Merge conflict resolved in https://github.com/AffiliateWP/AffiliateWP/pull/2378/commits/d3ec81d738d71eddba88de39ff789cf4d8211b56

**Comment by amdrew** [comment] 2017-10-04 22:22
@ramiabraham 👍 Needs the same treatment for the other emails that show when require approval is enabled from the misc settings

**Comment by ramiabraham** [comment] 2017-10-05 15:06
@amdrew In `affwp_notify_on_registration`, the only check to the `require_approval` setting is a statement that appends a link in the admin email to review all pending applications, if `require_approval` is enabled:

```php
if( affiliate_wp()->settings->get( 'require_approval' ) ) {
    $message .= sprintf( __( 'Review pending applications: %s', 'affiliate-wp' ), affwp_admin_url( 'affiliates', array( 'status' => 'pending' ) ) ) . "\n\n";
}
```

All of the other emails are notifications for affiliates. What should be added to those?

**Comment by pippinsplugins** [comment] 2017-10-05 16:38
I don't think anything needs to be added to those.

**Comment by amdrew** [comment] 2017-10-05 21:17
@ramiabraham @pippinsplugins Was referring to the divider lines that were added. Enable require approval from misc settings:

<img width="1425" alt="screenshot 2017-10-06 10 15 17" src="https://user-images.githubusercontent.com/52581/31252934-5b2c4f2a-aa7f-11e7-9476-b1310a6a67ae.png">

<img width="1429" alt="screenshot 2017-10-06 10 15 09" src="https://user-images.githubusercontent.com/52581/31252935-5b328bb0-aa7f-11e7-9413-aabdad1b8b90.png">

**Comment by ramiabraham** [comment] 2017-10-13 18:27
Sorry I think I'm confused - where should dividing lines be added?

**Comment by amdrew** [comment] 2017-10-13 21:30
@ramiabraham Take a look at this, note the lines in all the other sections, but the 2 at the bottom (shown in the screenshots above).

![screen shot 2017-10-14 at 10 29 25-fullpage](https://user-images.githubusercontent.com/52581/31567171-a60d4caa-b0ca-11e7-91ab-612102ca5dda.png)

**Comment by amdrew** [comment] 2018-01-14 06:04
@AffiliateWP/core Ready for testing. The other approval emails now have a header:

E.g.

<img width="990" alt="screen shot 2018-01-14 at 7 03 54 pm" src="https://user-images.githubusercontent.com/52581/34913287-b2e74634-f95d-11e7-8b6e-8694e246372f.png">

**Comment by pippinsplugins** [comment] 2018-01-15 01:19
Merge conflict resolved.

Looks like a _lot_ of tests have been broken by these changes so we'll need to carefully review and fix them (or the cause of them breaking).

@amdrew can you go ahead and finish your side of this? I'll then take over to resolve the tests.

**Comment by amdrew** [comment] 2018-01-22 06:49
@pippinsplugins 

1. The `affwp_email_referral_notifications` filter that was added to the `affwp_email_referral_notifications()` function has been removed. I see no need since the new referral notification email and the affiliate area checkbox option can now be controlled via the other new filter, `affwp_email_notification_enabled`. Plus, it was only meant to be a helper function.

2. The `affwp_email_notification_enabled` filter now allows not only specific emails to be controlled, but also on a per-affiliate level. 

Example:

``` php
function affwp_custom_email_notification_enabled( $enabled, $email_notification, $affiliate_id ) {
       
        // Disable a specific affiliate's new referral email notification. Will also hide the checkbox option for the affiliate in their Affiliate Area.
	if ( 'affiliate_new_referral_email' === $email_notification && 69 === $affiliate_id ) {
		$enabled = false;
	}

        // Disable the admin's new referral email notification, but only for the affiliate with an ID of 50. useful if an affiliate gets a tonne of referrals
        if ( 'admin_new_referral_email' === $email_notification && 50 === $affiliate_id ) {
		$enabled = false;
	}

	return $enabled;

}
add_filter( 'affwp_email_notification_enabled', 'affwp_custom_email_notification_enabled', 10, 3 );
```

**Comment by pippinsplugins** [comment] 2018-01-22 15:11
@gspice @michaelbeil this is ready for testing!

**Comment by amdrew** [comment] 2018-01-22 23:58
@pippinsplugins PR updated with requested changes.

**Comment by pippinsplugins** [comment] 2018-01-23 02:02
Yay, unit tests fixed!

**Comment by amdrew** [comment] 2018-01-23 22:50
@gspice @michaelbeil Let me know if you have any questions whatsoever on how to test a specific step, this needs to be tested thoroughly 👌

**Comment by amdrew** [comment] 2018-01-25 02:57
Made a small tweak to the wording of the first email. Previously it said:

Registration Email Options
Registration Email Subject
Registration Email Content

It's not clear based on the above text which email this is referring to. Since it's the email sent to the admin, and to match the other admin setting's text, I've changed it to:

Registration Email Admin Options
Registration Email Admin Subject
Registration Email Admin Content

This will hold us over until something like https://github.com/AffiliateWP/AffiliateWP/issues/2537 is implemented.

**Comment by amdrew** [comment] 2018-01-25 03:31
Something else I noticed. When an affiliate is `Pending` and you go to the edit use screen, you see this checkbox option to disable the affiliate accepted email:

<img width="667" alt="screenshot 2018-01-25 16 26 21" src="https://user-images.githubusercontent.com/52581/35369478-f3c867f4-01ec-11e8-9025-1048232c5591.png">

Now that you can disable that specific email globally, the checkbox should be removed. I.e:

<img width="659" alt="screenshot 2018-01-25 16 30 37" src="https://user-images.githubusercontent.com/52581/35369510-19317bac-01ed-11e8-9129-32d6be70b063.png">

Should mean:

<img width="379" alt="screenshot 2018-01-25 16 26 44" src="https://user-images.githubusercontent.com/52581/35369503-10b3d826-01ed-11e8-8545-8d97b5c9abf8.png">

**Comment by pippinsplugins** [comment] 2018-01-25 04:19
Looking good!

**Comment by michaelbeil** [comment] 2018-01-26 04:49
I tested everything, and could not find a fault.

I love these new email options.

**Comment by amdrew** [comment] 2018-01-29 00:52
@michaelbeil Could you also test the upgrade tests?

**Comment by gspice** [comment] 2018-01-30 22:59
I've been testing on my most heavily used testing site with WooCommerce and so far so good! My only suggestion thus far is currently when you install AffiliateWP for the first time, it sends emails to new affiliates automatically for acceptance, pending or rejected status....should those be checked by default or leave them as unchecked?  Also you might add to the note that is already there:

> Select which email notifications should be enabled. Uncheck all to completely supress all emails. 

Or something like that.

**Comment by amdrew** [comment] 2018-01-30 23:37
@gspice Great! 

In the current version of AffiliateWP, and when you install it for the first time, all affiliate emails are enabled by default (except for the 2 options that send emails to the admin), we just never had options to disable them. So it's essentially doing exactly what it does now, except providing the ability to disable them via checkbox options. I personally feel for that reason we should enable them by default.

Good point on the description underneath, I think that needs to be tweaked.

**Comment by michaelbeil** [comment] 2018-02-03 17:06
@amdrew what is the best way to do that?

**Comment by amdrew** [comment] 2018-02-04 22:28
@michaelbeil Instructions are listed above under the "Upgrade tests" heading: https://github.com/AffiliateWP/AffiliateWP/issues/948#issuecomment-359324257

Let me know if you are unsure of anything. Involves switching branches and deleting some rows from the database table.

**Comment by pippinsplugins** [comment] 2018-02-12 03:06
@michaelbeil could you please go ahead and give this a thorough test and share your exact results? Please confirm the expected behavior with screenshots throughout the testing process so we can be extra sure this is ready to go.

**Comment by michaelbeil** [comment] 2018-02-23 19:47
Upgrade routine went fine. The new settings look great:
![screen shot on 2018-02-23 at 20_45_33](https://user-images.githubusercontent.com/4752949/36613698-92b188ec-18da-11e8-95ea-685b6e7bb326.png)

Everything looks golden with all the email notifications!

Notify admin when a new affiliate has registered:
 
![screen shot on 2018-02-23 at 18_31_52](https://user-images.githubusercontent.com/4752949/36613327-6a34c5f6-18d9-11e8-8a79-c5a60aeb1a9f.png) 

 Notify admin when a new referral has been created:

![screen shot on 2018-02-23 at 18_32_39](https://user-images.githubusercontent.com/4752949/36613338-7a1eb4ae-18d9-11e8-8306-57cf72b91d69.png)


Notify affiliate when they earn a new referral:
![screen shot on 2018-02-23 at 18_33_46](https://user-images.githubusercontent.com/4752949/36613366-8fc2bdfa-18d9-11e8-93bc-7f6fd5a64b0e.png)


Notify affiliate when their affiliate application is accepted:
![screen shot on 2018-02-23 at 18_34_55](https://user-images.githubusercontent.com/4752949/36613467-e495c6ce-18d9-11e8-9b95-04d3b6804af1.png)


Notify affiliate when their affiliate application is pending:
![screen shot on 2018-02-23 at 18_35_30](https://user-images.githubusercontent.com/4752949/36613513-fad1b7ae-18d9-11e8-86b0-237e5159d989.png)


Notify affiliate when their affiliate application is rejected:
![screen shot on 2018-02-23 at 18_36_25](https://user-images.githubusercontent.com/4752949/36613548-104613dc-18da-11e8-90e9-a94fd7a5d93b.png)

**Comment by pippinsplugins** [comment] 2018-02-26 14:42
Merged!

**Closed by pippinsplugins** 2018-02-26 14:42 UTC
Labels: Has PR, Priority: High, enhancement
