### ISSUE TITLE
Deactivating a license key is not working

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1353] opened 2016-06-14 02:17 UTC
On AffiliateWP 1.8+, deactivating a license key no longer works. It appears like the settings are getting updated twice, once with the right value and possibly once with what seems to be a cached value.
   
This is probably because of the introduction of the new `set()` + `save()` method in 1.8. 

Perhaps `deactivate_license` on line 1065 of [class-settings.php](https://github.com/AffiliateWP/AffiliateWP/blob/master/includes/admin/settings/class-settings.php#L1065) needs to be refreshed.

**Comment by pippinsplugins** [comment] 2016-06-14 16:21
PR works great for me.

**Comment by DrewAPicture** [comment] 2016-06-14 16:23
OK, figured out what was going on here. Essentially this is a scope and memory pollution problem. In using the `set()` method with `$save = true`, we were polluting memory at runtime, which resulted in updating the options twice. Basically, we were overloading `$this->options` values, then saving from memory, but the core settings screen was then saving *again* with the old values, making the original post action moot.

The attached PR introduces a new optional parameter to the `save()` method, which facilitates saving directly without polluting memory. The recommendation going forward is that if we do further custom posting actions in settings, that we leverage the `save()` method directly. Obviously because it's a protected method, it's not accessible externally, and that's by design.

Added a PR: #1354

**Comment by michaelbeil** [comment] 2016-06-14 17:38
Works great here!

**Comment by DrewAPicture** [comment] 2016-06-14 18:47
Tested passed. Merged #1354.

**Closed by DrewAPicture** 2016-06-14 18:47 UTC
Labels: bug, needs testing
