### ISSUE TITLE
Referrals not being updated from "pending" to "unpaid" with "PayPal for WooCommerce" plugin

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#824] opened 2015-08-26 10:37 UTC
According to a customer support ticket, when PayPal Express is used via the "PayPal for WooCommerce" plugin, referrals are not being updated from `pending` to `unpaid` when the transaction is completed.

ticket: https://secure.helpscout.net/conversation/113344845/14985/
plugin: https://wordpress.org/plugins/paypal-for-woocommerce/

**Comment by sumobi** [comment] 2015-09-03 03:03
Some additional info here: https://wordpress.org/support/topic/paypal-express-orders-not-registering-with-affiliatewp-plugin?replies=8#post-7377433

**Comment by worldtravlr** [comment] 2015-09-03 13:48
@sumobi so you know if there is any kind of hack or code that might be able to temporarily fix this?  We are expecting about 20,000+ orders during our five day sale, so if there is a quick way to get these to be accepted instead of pending that would really help.

**Comment by pippinsplugins** [comment] 2015-09-03 14:26
@worldtravlr Possibly.

The plugin dev asked this on WordPress.org:

>>> Processing vs. Completed is really a matter of how you want to handle those orders. If you change them to Completed manually does it trigger what you need, by chance?

Can you tell me if that triggers it?

**Comment by worldtravlr** [comment] 2015-09-03 19:31
Thanks @pippinsplugins.  I may not be understanding the questions correctly and/or may not know what setting I would change, but the orders are being automatically completed one the payment is sent which I think is good an makes sense.  The issue is that the referrals are staying as pending for completed woocommerce orders.  Would it help me to try and change a completed to processing and then back to completed to see if that triggers the referral to change to accepted?

**Comment by pippinsplugins** [comment] 2015-09-03 22:27
When an order is completed, is it marked as Completed or as Processing?

**Comment by worldtravlr** [comment] 2015-09-03 22:51
When an order is complete it is marked as Complete automatically.  For CC transactions (via PayPal DoDirect via the same plugin) any Completed orders the affiliate referral is also marked as Accepted automatically, but for any Completed Orders via PayPal Express, the affiliate commission is always marked as Pending.

**Comment by pippinsplugins** [comment] 2015-09-06 01:24
According to the gateway author:

>>>Actually, our Express gateway should be leaving your orders as Processing. It wouldn't automatically update to Completed unless there is something else in place doing that.

Is that not happening?

**Comment by worldtravlr** [comment] 2015-09-06 01:29
Correct.  I think that is the default for non-digital products, but when a product in woocommerce is marked as Digital and Virtual, then there is the option to have it be marked as completed on successful payment.

http://docs.woothemes.com/document/digitaldownloadable-product-handling/#section-3

**Comment by pippinsplugins** [comment] 2015-09-06 01:59
Based on the supported thread with the plugin, it definitely appears to be due to a bug in the PayPal Express plugin.

Have you considered using the official PayPal Express integration? http://www.woothemes.com/products/paypal-express/

**Comment by worldtravlr** [comment] 2015-09-06 02:08
Thanks Pippin.  Yeah, I purchased that plugin, but the checkout flow is really strange and not intuitive as it goes like this:

Go to checkout page and either click pay with paypal express or enter billing info.  If you enter billing info and then later click pay via PayPal Express then after paying it brings you to the begignigng of the checkout again, but has your billing info already filled in.  You then have to go through any step on that page a again and then is click confirm payment where I bailiff you get dumped on another page to have a change to cancel and then finally have made your order.

With this plugin they put in their info, go to PayPal Express if selected and then more intuitively are sent to a final screen that is different from the checkout page and just has a quick summary of the costs for confirmation which I feel is much more frictionless.

**Comment by worldtravlr** [comment] 2015-09-06 02:08
Is there something I can recommend the PayPal express plugin developer could check on to see about fixing this issue on their end?

**Comment by pippinsplugins** [comment] 2015-09-06 02:12
That is a rather weird checkout flow.

I'm 99.99999% sure this issue is due to something in the PayPal Express plugin. None of the other gateways do this, so there's no cause for it to be due to AffiliateWP.

AffiliateWP works off of the standard WooCommerce update processes. As long as the gateway creates and updates the order statuses properly, AffiliateWP will work. In this case (and as the developer hinted at on WordPress.org), they've done something that makes the default status changes not occur in the standard order.

**Comment by worldtravlr** [comment] 2015-09-06 02:58
Thanks @pippinsplugins.  Yeah seems like there are a few issues they are working on fixing currently.  At this stage I think we will just plan to manually approve the pending referrals as I have confirmed that if the order is later set to cancelled/refunded, etc then the referral will correctly be decline/cancelled.  Thanks for checking into it and trying to find a solution on this end.

**Comment by worldtravlr** [comment] 2015-09-06 03:21
Agreed about the stage checkout flow.  I was surprised that the $100 plugin had a much less intuitive flow than the free option.

Looks like they agree the issue is on their end, so this can probably be closed as it is with their plugin and not AfiliateWP as you had thought:

https://wordpress.org/support/topic/paypal-express-orders-not-registering-with-affiliatewp-plugin?replies=12#post-7392240

Thanks again and sorry for the work on an issue that is not related to AffiliateWP.

**Comment by pippinsplugins** [comment] 2015-09-06 20:56
Ok closing this out then. I hope they're able to resolve it soon for you!

**Closed by pippinsplugins** 2015-09-06 20:56 UTC
Labels: bug, i:WooCommerce

**Comment by worldtravlr** [comment] 2015-09-06 20:58
Thanks so much @pippinsplugins me too :-)  All the best!

**Comment by worldtravlr** [comment] 2015-09-07 20:55
All fixed up with a single line of code @pippinsplugins - https://github.com/angelleye/paypal-woocommerce/commit/9e851415e98c2d3355a5c7391c63915851897b86 

Thanks to you and @sumobi for trying to help troubleshoot this and sorry for the time suck as it was never your issue to begin with.

**Comment by sumobi** [comment] 2015-09-07 23:24
@worldtravlr Awesome and no problem, glad it's working now! :+1:

**Comment by worldtravlr** [comment] 2015-09-08 00:09
Me too and thanks again for your always awesome support! :+1:  :+1:

**Comment by pippinsplugins** [comment] 2015-09-08 13:37
Excellent!
