### ISSUE TITLE
Strings on login/registration not being localized/translated

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#1993] opened 2017-02-08 18:30 UTC
User on this ticket sent in German translation file thinking we didn't have one.   Additional notes received from this user on the ticket below:

"Thanks! but this is not the usual GERMAN! it is German FORMAL!!! so de_DE_formal!
please don't mix it! the original version is fine I checked it already! but de_DE_formal.mo didn't exist yet! its different"

https://secure.helpscout.net/conversation/316598162/52612/?folderId=1170842

[Lang-Files-de_DE_formal.zip](https://github.com/AffiliateWP/AffiliateWP/files/761578/Lang-Files-de_DE_formal.zip)

Possibly related, this ticket from Feb 6th user was having issue with German DE on the registration and login screens.  

https://secure.helpscout.net/conversation/313868083/52246/?folderId=1170842

@DrewAPicture created these screen shots while troubleshooting it. 

![german-de-register](https://cloud.githubusercontent.com/assets/3018245/22751517/88524b60-ede9-11e6-8fe5-b03a2e2b5991.png)

![german-de-login](https://cloud.githubusercontent.com/assets/3018245/22751520/8beccb38-ede9-11e6-8f91-2135dd3670e3.png)

**Comment by flowdee** [comment] 2017-02-15 01:55
Indeed these are the more common German translations.

**Comment by DrewAPicture** [comment] 2017-03-24 19:37
I've narrowed this down to being caused by strings being notated as fuzzy and therefore not output to the mo files by potomo. This appears to be intentional behavior, so we'll have to look at whether we can _un_fuzzy these pot files to resolve the problem.

**Comment by DrewAPicture** [comment] 2017-06-01 06:56
Added a PR that properly unfuzzies translations. I went through the files one at a time in Poedit and unfuzzied them. A few required some manual fixing but not all of them and not a lot of effort (10 or 12 fixes per file).

PR: #2246

**Comment by pippinsplugins** [comment] 2017-06-01 11:53
PR looks good, merged!

**Closed by pippinsplugins** 2017-06-01 11:53 UTC
Labels: bug, Has PR, i18n, needs testing
