### ISSUE TITLE
Paid Memberships Pro - Per-membership commission amounts

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/AffiliateWP#498] opened 2015-01-08 01:58 UTC
Like per-product commission amounts, but for membership levels

**Comment by codelion7** [comment] 2015-03-17 00:01
I'm about to implement this myself, but I'm wondering if it's best to add the settings for each membership level within PMP's "Edit Membership Level" screen, or to simply add the settings to the "Integrations" tab  of AffiliateWP. What do you guys think is best?

**Comment by pippinsplugins** [comment] 2015-03-17 00:38
If vote for within the membership level edit screen so it is consistent
with our other integrations.

**Comment by sumobi** [comment] 2015-03-17 01:36
:+1:

**Comment by codelion7** [comment] 2015-03-17 12:25
Alright, will do.

**Comment by pippinsplugins** [comment] 2015-04-29 02:52
#670

**Comment by pippinsplugins** [comment] 2015-08-31 15:18
@codelion7 do you think you'll have the PR for this updated in the next day or two?

**Comment by codelion7** [comment] 2015-08-31 21:30
@pippinsplugins, I honestly don't think that I'll get to finishing this until the weekend. I'm going to be travelling tomorrow, and then, I'll be finishing MLM version 1.0.5 for the next few days.

**Comment by pippinsplugins** [comment] 2015-08-31 22:47
Ok I'll try and extract them from the previous PR.

**Comment by pippinsplugins** [comment] 2015-09-06 12:12
Moving to 1.8

**Comment by michaelbeil** [comment] 2016-04-12 00:13
Do we want to keep this in 1.8?

**Comment by pippinsplugins** [comment] 2016-04-12 00:15
Let's try

**Comment by michaelbeil** [comment] 2016-04-12 00:16
Ok. It looks like we could parse through some of the previously referenced PRs and add this option to the PMP membership level screen fairly easily.

**Comment by DrewAPicture** [comment] 2016-04-23 22:47
Added a PR: #1226

**Comment by pippinsplugins** [comment] 2016-04-25 03:16
@DrewAPicture Looking good overall. What's the purpose of the `product_type` parameter? Does not look like that should be required since we can just consider PMP levels to be products (similar to how they are treated in MemberPress and Restrict Content Pro integrations).

**Comment by DrewAPicture** [comment] 2016-04-25 04:21
@pippinsplugins The problem is lack of context. Injecting a new referral rate in between the global rate and the affiliate rate is a little tricky without completely overriding `calculate_referral_amount()` (which I looked at, but it was a huge rabbit hole, and raises the future maintenance burden).

I found that overriding `get_product_rate()` was the best option for injecting the new referral rate, mostly because a membership is a product, but in this case we don't pass a product ID and it doesn't use posts or post meta.

The 'product_type' parameter was added to allow selectively triggering `get_product_rate()` (which can then be overridden to work around the lack of posts and post meta).

**Comment by DrewAPicture** [comment] 2016-04-25 04:33
@pippinsplugins After thinking about it a little bit, I've removed the 'product_type' logic and instead passed the membership level as the product ID to then trigger `get_product_rate()` which is then overridden in the sub-class.

**Comment by pippinsplugins** [comment] 2016-04-25 04:47
>>>After thinking about it a little bit, I've removed the 'product_type' logic and instead passed the membership level as the product ID to then trigger get_product_rate() which is then overridden in the sub-class.

That was going to be my suggestion :+1:

**Comment by pippinsplugins** [comment] 2016-04-28 18:46
The option to disable referrals does not seem to be working properly. Referrals are still created.

**Comment by pippinsplugins** [comment] 2016-04-28 18:51
Fixed ^

**Closed** 2016-04-28 18:52 UTC
Labels: enhancement, Has PR, i:Paid Memberships Pro, needs testing
