### ISSUE TITLE
Appending referral variable to site URL redirects to blog archive

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1409] opened 2016-07-06 01:01 UTC
When you append the referral variable onto the end of the site URL (e.g. test.com/ref), and you happen to have a slug of `ref` for a post or page, you are redirected to the blog archive page if your home page is set to a static page. This only happens with a _pretty affiliate link_. Non-pretty affiliate links do not exhibit this behavior (e.g. test.com/?ref).
  
**Proposal**:  
- If there is no slug that is the same as the referral variable, 404
- If a slug is present that is the same as the referral variable, we should just ignore the referral variable and go to whatever post/page is set to that slug

**Comment by pippinsplugins** [comment] 2016-07-06 01:08
Moving to 1.9 since this is a minor issue that only happens when URLs are used incorrectly.

**Comment by pippinsplugins** [comment] 2016-08-31 02:35
@michaelbeil @sumobi mind giving this a test?

**Comment by michaelbeil** [comment] 2016-08-31 02:47
I am still redirected to the blog archive when a static page is set as the home page, and I have a post slug of `ref`: test.com/ref redirects to the blog archive.

**Comment by pippinsplugins** [comment] 2016-08-31 03:00
If you remove the post (100% delete, not just trash), does the redirect stop happening?

**Comment by michaelbeil** [comment] 2016-08-31 03:42
Negative.

**Comment by sumobi** [comment] 2016-08-31 05:46
@pippinsplugins @michaelbeil 

1. I created a new page with a slug of `ref`.
2. I have the static front page set to WP's "sample page"
3. I use a URL of `http://issues.affwp.dev/ref/`

Result: The "sample page" static front page is loaded with a URL of `http://issues.affwp.dev/ref/`. The master branch (as per the issue) loads the blog archive page.

I believe (as per Michael's initial proposal) that this should actually load the `/ref` page i created, correct? (rather than the sample page)

> If a slug is present that is the same as the referral variable, we should just ignore the referral variable and go to whatever post/page is set to that slug

Note: this is confusing.

**Comment by pippinsplugins** [comment] 2016-08-31 13:48
I was testing without a page with a slug of `ref`. Will try again.

**Comment by pippinsplugins** [comment] 2016-08-31 14:18
It works fine for me.

1. Set home page to static `Sample Page`
2. Created a page with a slug of `ref`
3. Went to home page--loads fine
4. Went to `/ref`--loads fine
5. Went to `/ref/1`--loads fine _and_ sets affiliate cookies

**Comment by pippinsplugins** [comment] 2016-08-31 17:42
Ok nvm, I've replicated the problem.

**Comment by pippinsplugins** [comment] 2016-08-31 17:43
@michaelbeil Can you please test `issue/1409` again?

**Comment by michaelbeil** [comment] 2016-08-31 18:13
It works fine for me with a page that has a slug of ref.

1. Set home page to static page
2. Created a page with a slug of `ref`
3. Went to home page--loads fine
4. Went to `/ref`--loads the Ref page fine
5. Went to `/ref/1`--loads fine _and_ sets affiliate cookies

However, I am redirected to the home page when I create a post with a slug of `ref`.

1. Set home page to static page
2. Created a post with a slug of `ref`
3. Went to home page--loads fine
4. Went to `/ref`--loads the home page instead
5. Went to `/ref/1`--loads fine _and_ sets affiliate cookies

This absurdity is almost going beyond what is sane when thinking about running a legit site. One should simply not be creating a page/post with the same slug as the referral variable. #nufsaid

**Comment by ramiabraham** [comment] 2016-08-31 18:22
Confirmed @michaelbeil's testing entirely. Rather than _accounting_ for a posttype slug equal to the referral variable, we could display a notice, possibly only within a debug context, if a posttype has a slug matching the referral variable in use.

**Comment by pippinsplugins** [comment] 2016-08-31 18:23
Ok pushed a tweak to resolve it for posts too.

It's a slippery slope if we start trying to prevent this on every post type. Perhaps at that point we just have to say "to bad"?

**Comment by ramiabraham** [comment] 2016-08-31 18:24
+1 to that

**Comment by pippinsplugins** [comment] 2016-08-31 18:26
Ok please test once more with a post named `ref`. If that works fine, I'm going to merge and close.

**Comment by michaelbeil** [comment] 2016-08-31 18:32
Getting a 404 on a post with a slug of `ref`.

**Comment by ramiabraham** [comment] 2016-08-31 18:33
Now that's interesting. Variable behavior here. 

At https://github.com/AffiliateWP/AffiliateWP/commit/e65c978227947ede79f71ea615cdcc47a7475660, _no_ cookie is set on these conditions:

- Static front page
- `post` with slug of `ref` with status of `publish`
- `pretty` urls

**Closed** 2016-08-31 18:50 UTC
Labels: bug
