### ISSUE TITLE
Entering a 1% commission rate changes rates to 100%

### ISSUE THREAD

**Issue by sumobi** [affiliatewp/AffiliateWP#723] opened 2015-06-14 22:34 UTC
If you enter `2` in the `Referral Rate` field (general settings) all affiliate rates are set to `2%` as expected. If you enter `1` however, all affiliate rates are changed to `100%`. 

A workaround for the time being is to set the rate to `0.01`. Since 2 gives 2% I would expect 1 to give 1% also.

![screen shot 2015-06-15 at 10 31 49 am](https://cloud.githubusercontent.com/assets/52581/8150747/ccb22662-1349-11e5-9d49-cb204b946f8d.png)

![screen shot 2015-06-15 at 10 32 01 am](https://cloud.githubusercontent.com/assets/52581/8150748/ccb23508-1349-11e5-8146-cdf737a85b3e.png)

**Comment by sumobi** [comment] 2015-07-28 08:51
This is fixed in my testing

**Comment by pippinsplugins** [comment] 2015-08-27 21:39
This is NOT resolved in #826 (previously #751).

Entering 1 with a percentage type on the affiliate's edit screen still changes it to 100.

**Comment by pippinsplugins** [comment] 2015-08-27 21:40
Entering `1.0` also changes it to 100.

**Comment by pippinsplugins** [comment] 2015-08-27 21:42
Entering `0.01` works but then gets changed to `1`, so if the affiliate is updated again, it will be changed to `100`.

**Comment by pippinsplugins** [comment] 2015-08-27 21:44
Note: entering `1` on a product rate and setting the affiliate's rate to default does result in the proper `1%` rate.

**Comment by sumobi** [comment] 2015-08-27 21:54
Getting the same behaviour

**Comment by pippinsplugins** [comment] 2015-08-27 21:55
Yay not crazy!

**Comment by pippinsplugins** [comment] 2015-08-27 21:58
When entering `1`, it's getting stored as `0` in the database: 
![screen shot 2015-08-27 at 4 57 48 pm](https://cloud.githubusercontent.com/assets/1034109/9534269/d11d3bc0-4cdc-11e5-8887-c82ad831e2b1.png)

**Comment by pippinsplugins** [comment] 2015-08-27 22:02
Whoops, no it's not. `100` entered on `edit` and `100` saved in DB

**Comment by pippinsplugins** [comment] 2015-08-27 22:27
It's getting changed to `100` as soon as the value is retrieved from the column . . . .

**Comment by fjarrett** [comment] 2015-08-28 22:58
@pippinsplugins Sorry if I'm totally off base, I'm a little out of the loop, but that type of behavior sounds like it's being caused by the upgrade routine. Could be solved by updating the `affwp_version` option in the database to `1.7` or higher.

**Comment by pippinsplugins** [comment] 2015-08-31 15:05
@fjarrett You're 100% correct. It was the upgrade routine. That occurred to me last night before seeing your comment. You're much faster than me :D

**Comment by pippinsplugins** [comment] 2015-08-31 15:06
This works great now!

**Comment by pippinsplugins** [comment] 2015-08-31 15:06
@sumobi Could you give this one more round of testing before we merge it in?

**Comment by sumobi** [comment] 2015-09-01 01:21
:+1: will do

**Comment by sumobi** [comment] 2015-09-01 07:49
@pippinsplugins 

The `Referral Rate Type` under Affiliates -> Settings reverts back to `Percentage` if `Flat USD` is set. Can you replicate?

**Comment by pippinsplugins** [comment] 2015-09-02 15:29
Replicated.

**Comment by pippinsplugins** [comment] 2015-09-02 15:33
It's not caused by this PR though. It happens in `release/1.7` too.

**Comment by pippinsplugins** [comment] 2015-09-02 15:39
It's caused by changes in #724

**Comment by pippinsplugins** [comment] 2015-09-02 15:44
Fixed. @sumobi can you test this again now?

**Comment by sumobi** [comment] 2015-09-03 04:37
@pippinsplugins nice that's fixed. Will continue testing.

**Comment by sumobi** [comment] 2015-09-03 04:58
@pippinsplugins You can set an affiliate's referral rate to 50.5 on the edit affiliate screen but if you try 50.5 on the main settings page it rounds it to 50.

**Comment by sumobi** [comment] 2015-09-03 08:22
@pippinsplugins The referral rate input field steps in increments of .01 when you use the arrows. I think it should step in whole numbers, but still allow the smaller increments if you typed them in.

**Comment by pippinsplugins** [comment] 2015-09-03 14:27
I agree on that. Will make adjustments.

**Comment by pippinsplugins** [comment] 2015-09-03 20:37
@sumobi fixed.

**Comment by pippinsplugins** [comment] 2015-09-03 20:38
@sumobi the step can't be increased. That determines the number of digits that can be entered.

**Comment by sumobi** [comment] 2015-09-05 08:15
@pippinsplugins kk

**Comment by sumobi** [comment] 2015-09-05 08:15
Can't spot anything else on this

**Closed** 2015-09-05 19:02 UTC
Labels: bug
