### ISSUE TITLE
Auto register specific user roles as affiliates

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#1625] opened 2016-09-20 21:15 UTC
A user asked about auto registering certain users roles as affiliates. This could be useful if there is one specific role that the site owner wants to be registered as an affiliate automatically.

**Comment by pippinsplugins** [comment] 2016-09-21 00:55
Duplicate of https://github.com/AffiliateWP/AffiliateWP/issues/1276

**Closed by pippinsplugins** 2016-09-21 00:55 UTC
Labels: enhancement
