### ISSUE TITLE
Referral is generated at $0.00 when Simple Sales Tax plugin is active

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/AffiliateWP#2208] opened 2017-05-04 22:39 UTC
A customer is experiencing an issue whereby referrals are generated at $0.00 when the Simple Sales Tax plugin is active (when they should be a dollar amount). When the plugin is deactivated, referrals are generated at the correct amount. I'm not sure if this is an issue within AffiliateWP or within Simple Sales Tax, but would be good to look into. I have tested by activating and deactivating various other plugins, and by enabling and disabling various features in AffiliateWP, but it seems that referrals are generated at $0.00 when this plugin is active.

I replicated this locally by simply having AffiliateWP, WooCommerce and Simple Sales Tax active, and trying to generate a referral. A referral is generated, but at $0.00 when it should have been $20, for a $100 product.

I've saved the Simple Sales Tax plugin in Dropbox for testing purposes.

Ticket ref: https://secure.helpscout.net/conversation/357786709/58400/?folderId=205529

**Comment by sumobi** [comment] 2017-05-04 23:08
Replicated also by just activating the plugin. In addition to the amount being `0.00`, the referral's description is blank.

Tracked it down so far to this line:

`add_action( 'woocommerce_new_order', array( __CLASS__, 'add_order_meta' ), 10, 1 );`

Comment that out and the referral is correctly generated. Will dig a little deeper.

**Comment by sumobi** [comment] 2017-05-04 23:26
Commenting out `self::get_order( $order_id );` in the `add_order_meta()` method brings referrals back to life. Looks like `add_order_meta()` is only for logging:

> Sets WooTax order meta when a new order is created
> Inserts a log entry indicating an order has been created if logging is enabled

At least (so far) it doesn't seem to be tax related :)

**Comment by sumobi** [comment] 2017-05-05 00:00
It looks like the tax plugin _may_ be doing something to the WooCommerce order ID. AffiliateWP sets a `0.00` amount first and then loops through each product to calculate the amount. Since it's still at `0.00` it would imply that it isn't able to retrieve the amount for each product based on the order (perhaps wrong order ID?). This also explains why the description isn't being added to the referral.

Something related to their get_order() method:

``` php

/**
	 * Get WC_WooTax_Order object
	 *
	 * @param (int) $order_id ID of WooCommerce order to load
	 */
	public static function get_order( $order_id = -1 ) {
		if ( is_null( self::$order_instance ) ) {
			self::$order_instance = new WC_WooTax_Order();
		}

		if ( self::$order_instance->order_id != $order_id ) {
			self::$order_instance->load( $order_id );
		}

		return self::$order_instance;
	}
```

**Comment by gspice** [comment] 2017-05-05 20:42
This sounds exactly like what was happening on Brad's ticket with the AffiliateWP Integration for WooCommerce Currency Switcher....zero amount referrals and a blank description.

**Comment by pippinsplugins** [comment] 2017-05-08 16:20
@sumobi could you please reach out to the Simple Tax plugin authors and see if they can provide any insight here? support@simplesalestax.com

**Comment by pippinsplugins** [comment] 2017-05-09 01:38
I have gotten closer to tracking this down but not quite.

When Simple Sales Tax is active, `$this->order = apply_filters( 'affwp_get_woocommerce_order', new WC_Order( $order_id ) );` in `add_pending_referral()` fails to return _any_ data. It's simply empty.

When `self::get_order( $order_id );` is removed from the Simple Sales Tax plugin, everything works again, as @sumobi pointed out. `self::get_order( $order_id );` is somehow overwriting or clearing the cached order data retrieved from WooCommerce during the purchase creation process. _Why_ this happens I'm unclear.

I reached out to some Woo folks and they pointed me to this issue https://github.com/woocommerce/woocommerce/issues/13579

Simple Sales Tax uses the `woocommerce_add_order_item_meta` and `woocommerce_add_order_fee_meta` hooks. These, as pointed out in the issue above, have been deprecated in WooCommerce 3.0.x.

I'm going to reach out to Simple Sales Tax support to see if they can get an update released for their plugin.

**Comment by pippinsplugins** [comment] 2017-05-09 01:39
Oh, I've also confirmed this problem does not occur when using WooCommerce 2.6.x.

**Comment by gspice** [comment] 2017-05-09 19:20
Got another one of these - still working on troubleshooting on customer's site.  Possible plugins are shipping, wholesale pricing.

https://secure.helpscout.net/conversation/356054725/58196/?folderId=1170842

**Comment by pippinsplugins** [comment] 2017-06-09 20:53
Another case: https://secure.helpscout.net/conversation/378556436/60781/?folderId=205527

This one doesn't have any tax plugins.

**Comment by pippinsplugins** [comment] 2017-06-10 02:52
Update on ticket above: it wasn't a bug. It was our `Allowed Products` add-on causing it to _appear_ to be a bug.

The site owner hadn't declared any products in the Allowed Products section, so _no_ products were allowed, which resulted in $0.00 referrals on every purchase.

**Comment by gspice** [comment] 2017-06-12 23:53
Update on my ticket above:
https://secure.helpscout.net/conversation/356054725/58196/?folderId=205529

Andrew tracked it down to a plugin called:
WooChimp, Version 2.2.1 from RightPress

When de-activated the referral amounts were corrected and the description was populated.

**Comment by pippinsplugins** [comment] 2017-08-08 19:19
No new cases have been reported of this so it appears it has been resolved through WooCommerce updates. Leaving open just in case though.

**Comment by pippinsplugins** [comment] 2017-12-29 01:21
Still no new cases of this, closing.

**Closed by pippinsplugins** 2017-12-29 01:21 UTC
Labels: bug
