### ISSUE TITLE
Visits: Usernames with dashes append dash and characters following to Landing Page entry.

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2419] opened 2017-10-23 20:55 UTC
Reported on this support ticket:
https://secure.helpscout.net/conversation/450464320/68649?folderId=1170842

Reproduced with:
* Created username:  `user-name`
* Use in this format:    http://mysite.com/mypage/ref/user-name
* Creates a Visit showing the referring Landing Page as : http://mysite.com/mypage-name

If the link is formatted like:  http://mysite.com/mypage/?ref=user-name that works fine.  

This is visible in the afffiliate-area/Visits and also in admin Visits.

**Comment by DrewAPicture** [comment] 2017-10-25 18:54
Hmm. I'm unable to reproduce this. Since dashes aren't allowed in usernames on multisite, anybody else testing may need to create a username and manually change it to include the dash via their SQL editor.

In attempting to follow the steps to reproduce, I generated a test referral against a page on the site with the referral var of  `ref`. In my testing, the visit came through with the expected URL and the cookie was set to the affiliate ID as expected.

![Visit](https://cl.ly/0h1r0w343k0g/Screen%20Shot%202017-10-25%20at%2012.52.08%20PM.png)

**Comment by gspice** [comment] 2017-10-25 20:37
@DrewAPicture So the actual page link was http://affiliate.dev/sample-page-name/ ?  Or was it http://affiliate.dev/sample-page and the `-name` was added?

**Comment by DrewAPicture** [comment] 2017-10-25 20:43
Oh, good call. I didn't even notice that! :-)

**Comment by DrewAPicture** [comment] 2017-11-08 23:20
PR with two new tests: #2449.

Moving to the 2.1.8 milestone.

**Comment by pippinsplugins** [comment] 2017-11-10 19:20
@gspice could you give this a test?

**Comment by pippinsplugins** [comment] 2017-11-10 19:20
@amdrew you as well please?

**Comment by amdrew** [comment] 2017-11-10 22:15
Works well for me.

**Comment by gspice** [comment] 2017-11-14 03:11
Tested with username `test-user` and it works correctly.

**Closed** 2017-11-14 03:49 UTC
Labels: bug, Has PR, Priority: Low
