### ISSUE TITLE
Show Payouts totals in Reports

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/AffiliateWP#1997] opened 2017-02-08 22:56 UTC
Similar to seeing Referrals, Visits, etc in Reports, it would be very cool to be able to see Payouts totals filtered by date range in the Reports section of AffiliateWP. This would allow site owners to keep an eye on how much they are paying out their affiliates each week/month/year/custom, etc.

Related: #1996

**Comment by DrewAPicture** [comment] 2017-02-08 23:00
Which section of Reports, specifically? Affiliates or Referrals? Currently we show a payouts total in Affiliates I believe.

**Comment by wordmaid** [comment] 2017-02-08 23:02
On its own tab, possibly?

**Comment by DrewAPicture** [comment] 2017-02-08 23:18
Typically, we'd want to build out a tab as a collection of related information where we could show quick stats, trend data, and more. And realistically, a payout total for a date range is already reflected in the date-based "Paid Earnings" tile on Reports > Referrals. So maybe I'm missing something. :-)

**Comment by pippinsplugins** [comment] 2017-02-09 23:01
I think there is enough data. Some items that could be shown:

1. Graph of payout amounts over time (primarily year and month)
2. Number of affiliates paid
3. Number of payouts processed
4. Average payout amount
5. Average monthly payout
6. Average daily earnings

**Comment by DrewAPicture** [comment] 2017-02-10 00:02
OK. We already show an average payout tile on the Affiliates tab, so that could come over.

As for average earnings, I'd probably not limit it to _daily earnings_, just make it dependent on the date filters – more flexible.

Either way, I think we'll want to be careful about blurring intent between referrals and payouts. For instance, on Referrals, we show a lot of _earnings_-specific data. Maybe it would be good to separate out _paid_ vs _unpaid_ earnings, moving the paid metrics to a new Payouts tab and keeping unpaid with Referrals, for instance.

Another interesting tile idea:

* "Average turnaround" for either the referrals or payouts tab – the average amount of time between generation and payout.

**Comment by DrewAPicture** [comment] 2017-02-10 01:10
Started a PR with two initial tiles. Working on the other suggested here. PR: #2002.

Separately: What would we like to show in a graph on this page?

**Comment by wordmaid** [comment] 2017-02-10 03:52
@DrewAPicture _Paid Earnings_ as shown in the Referrals tab in Reports are not the same as a "Payout total".

- Paid Earnings shows the total dollar amount of **referrals that were _generated_ within the specified date range** (with a Paid status)
- Payout Total is the total money **_physically paid_ to affiliates** within the specified date range.


Here's an example:
1. For the month of December, my Unpaid referrals total $100.00.
2. On the 10th of January, I pay my affiliates via PayPal Payouts. I specify no "From" date and only specify a "To" date of the 31st of December.
3. My **Payout Total** comes to $300.00.
4. This is because I actually also have $200.00 worth of Unpaid referrals which were generated in November. These referrals are then paid in this January payout because I did not specify a "From" date.


In the Referrals tab in Reports:
- The November _Paid Earnings_ will be $200.00, which is the total dollar value of referrals _generated_ in November. 
- The December _Paid Earnings_ will be $100.00, which is the total dollar value of referrals _generated_ in December. 
- But my _**Payout Total**_ in January is $300.00, because I actually **paid out** both November and December referrals.

Therefore my Payout total is different to the Paid Earnings.

A Payout could actually collect numerous Unpaid referrals from 1 month ago, 3 months ago, 1 year ago, etc, if no "From" date is specified (this is how we do it ourselves).

I would love to see the graph show the Payout Total dollar amount, monthly by default (with the date range options we provide in the other tabs). This would allow site owners to quickly see how much money was **physically paid to affiliates** within a specific date range (not the total of the referrals generated in that period).

**Comment by DrewAPicture** [comment] 2017-02-10 16:05
OK, makes sense, though I do think it's somewhat peculiar that there's a discrepancy between _paid referrals_ and _payouts_ since the only way to have a paid referral that's not part of a payout is to manually change the status or do it programmatically. Marking a referral or bulk referrals as paid generates a payout, as does generating an actual payout. The whole point of payout logs is to effectively log the marking of referrals as paid, regardless of how that came about, and regardless of whether somebody is using an addon like PayPal Payouts. So personally, I think that any status change to paid should generate a payout ;)

For the graph, would you want to show only the _total_ for the month or daily totals if on a month-based time range? I ask because if we show only the monthly total and the default range is _This Month_ there is only going to be a single dot on the graph. For most of the graphs, we show different summed totals for day vs month vs quarter vs year vs custom date ranges.

**Comment by DrewAPicture** [comment] 2017-02-10 16:09
Updated my comment. I got it :)

**Comment by pippinsplugins** [comment] 2017-02-10 17:43
Let's do daily totals on the graph.

And 💯 to everything @wordmaid said :)

**Comment by DrewAPicture** [comment] 2017-02-10 17:49
@pippinsplugins OK, and do you want to do monthly totals on the "year" filters, weekly on the "quarter" filters?

**Comment by pippinsplugins** [comment] 2017-02-10 17:51
Yeah that sounds good.

**Comment by DrewAPicture** [comment] 2017-06-01 19:55
I think [this comment](https://github.com/AffiliateWP/AffiliateWP/issues/2101#issuecomment-304989978) from @pippinsplugins was intended to be posted here:

> @DrewAPicture if we could also include a tile that shows the average / total number of referrals in payouts, that would be swell.

**Comment by pippinsplugins** [comment] 2017-06-01 22:45
Whoops, yes, that is correct :)

**Comment by pippinsplugins** [comment] 2017-06-06 21:42
@DrewAPicture Let's add a `Reports` button to the Affiliates &rarr; Payouts screen:
<img width="624" alt="screen shot 2017-06-06 at 4 40 45 pm" src="https://user-images.githubusercontent.com/1034109/26853282-02aabf9c-4ad7-11e7-9e02-1f45f619214a.png">

**Comment by pippinsplugins** [comment] 2017-06-06 21:47
I'm seeing an issue with the payouts graph:
<img width="1090" alt="screen shot 2017-06-06 at 4 41 41 pm" src="https://user-images.githubusercontent.com/1034109/26853474-c8ade610-4ad7-11e7-8f91-3ebb890592c1.png">

**Comment by DrewAPicture** [comment] 2017-06-06 21:48
@pippinsplugins Added the button in df69086.

**Comment by DrewAPicture** [comment] 2017-06-06 21:50
@pippinsplugins Try it after ef6c8d5. I accidentally left a `log_it()` call in the `get_data()` method.

**Comment by pippinsplugins** [comment] 2017-06-06 22:01
@DrewAPicture graph works now, but I get a PHP notice:

array_key_exists(): The first argument should be either a string or an integer	
wp-content/plugins/affiliate-wp/includes/class-referrals-db.php:578	

Same notice happens on wp-content/plugins/affiliate-wp/includes/class-payouts-db.php:572

**Comment by pippinsplugins** [comment] 2017-06-06 22:04
@DrewAPicture looks like we have a sneaky button :)
<img width="451" alt="screen shot 2017-06-06 at 5 03 50 pm" src="https://user-images.githubusercontent.com/1034109/26854066-27258c14-4ada-11e7-85b4-af718446f884.png">

**Comment by DrewAPicture** [comment] 2017-06-07 04:26
The Filters form is fixed as of 3c95712f3aa776ecf97638a2320a42eec7f41e32.

And in e080f36 I've added primer values to the data arrays for the start and end date filters to avoid the rendering issues in the graph. This is not unlike how a similar problem is mitigated already in the affiliate registrations graph.

**Comment by DrewAPicture** [comment] 2017-06-07 06:04
Also, the `array_key_exists()` notices were related to passing array values to the `fields` argument, mitigated now that #2254 has been merged.

**Comment by DrewAPicture** [comment] 2017-06-07 16:58
@pippinsplugins I believe all of your feedback has been addressed. Can you please retest? <3

**Comment by pippinsplugins** [comment] 2017-06-07 19:47
@DrewAPicture this is working great for me now! Merging.

**Comment by DrewAPicture** [comment] 2017-06-11 17:55
Reopening because the code for modifying the tiles for the affiliate filter got missed. Whoops!

**Comment by DrewAPicture** [comment] 2017-06-11 17:59
PR: #2272

Adds affiliate-specific versions of all tiles on Reports > Payouts.

Without the filter set:
![without filter](https://cl.ly/1U070y2z0M0p/Screen%20Shot%202017-06-11%20at%2011.57.50%20AM.png)

![with filter](https://cl.ly/441g1F2f3u22/Screen%20Shot%202017-06-11%20at%2011.58.24%20AM.png)

**Comment by pippinsplugins** [comment] 2017-06-12 02:57
Looks great, merged!

**Closed by pippinsplugins** 2017-06-12 02:57 UTC
Labels: enhancement, Has PR
