### ISSUE TITLE
wp_campaigns table is being corrupted when BackupBuddy is run

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/AffiliateWP#957] opened 2015-11-10 16:57 UTC
We’ve had several reports of the campaigns table being corrupted. The why is unknown. 

https://secure.helpscout.net/conversation/137707542/20938

**Comment by michaelbeil** [comment] 2015-11-10 17:44
One user is on Digital Ocean with ServerPilot and is not familiar with DB stuffs, but excluded the campaigns table and the backup went perfect.  
 
Response from BackupBuddy support:
> Whenever that error comes up, it usually mentions a specific database table:

> 18:44:46.63 24.34sec 23.86MB Error #857835: Unable to get table creation SQL for table sss_affiliate_wp_campaigns. Result: 1. Verify that it exists and mysql permissions allow this. If you manually included this as an additional table, make sure it is the correct table name.

> Specifically this database table:
sss_affiliate_wp_campaigns

> This indicates that BackupBuddy asked the database server for the sql statement(s) that would create the table in a new database but the database server was unable to return those details for some reason. This could indicate some corruption in the database for example, but we don't have any additional information in this case.

> Does this database table belong to any plugin that you are currently using? If not, then you might simply choose to try and delete the table although when we have seen similar database server issues in the past it has required some intervention from the host to determine what is the problem on their database server.

> If you still need the table then you may be able to repair it using your host's control panel database management tools.

> Alternatively you can refer to your host support who will be able to investigate the database problem on their server with much more detail than either you or we can and should be able to resolve the problem for you. Ultimately you may need to refer to the developers of the associated plugin for advice on how to recover.

> In the meantime you can exclude that table from the backup using the table exclusions capability on the Settings page.
BackupBuddy -> Settings -> General Settings -> Database Defaults ->

**Comment by michaelbeil** [comment] 2015-11-11 19:07
https://secure.helpscout.net/conversation/138014437/21017/

**Comment by pippinsplugins** [comment] 2016-04-18 16:26
I propose we close and tag as `wontfix`. This is not a bug in AffiliateWP; it's a bug in the migration plugins not properly respecting views.

**Closed by pippinsplugins** 2016-04-18 16:26 UTC
Labels: bug

**Comment by michaelbeil** [comment] 2016-04-18 18:10
Totally fine with me. One customer was recently migrating AffiliateWP, and after I explained that the campaigns were not a table, but a view, they adjusted the export and all went well. Not sure what tool they were using, but could be helpful if other customers run into this issue.

**Comment by pippinsplugins** [comment] 2016-04-18 18:16
:+1:
