### ISSUE TITLE
Importing referrals from CSV completes but count is off, no referrals are imported.

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/AffiliateWP#2407] opened 2017-10-06 18:09 UTC
Reported on this HS ticket:
https://secure.helpscout.net/conversation/442110287/67764/?folderId=1170842

Staging database login credentials and CSV file attachment available on the above ticket.

1. Went to _Affiliates > Tools > Export/Import_ to **Import Referrals**
2. Used CSV file which was exported from another site with AffiliateWP
3. Import says complete for 59 referrals (seems to be going by the affiliate count?), the referral CSV file has 2,561 entries.
4. Checked the _Affiliates > Referrals_ page in the admin and it is empty.

I used username in the field mapping and verified there are matches on the usernames.

**Comment by DrewAPicture** [comment] 2017-10-09 16:43
Without having looked into it yet, I'm guessing the problem is similar to
the garbage collection failure in that the batch_id property isn't set
further up the stack in certain circumstances. I'll get into it.

**Comment by DrewAPicture** [comment] 2017-10-25 18:37
I'm thinking his might be related to/the same bug that was just fixed in #2420.

**Comment by gspice** [comment] 2017-10-25 21:01
@DrewAPicture Tested the import again with fix #2420 and it all works as expected!

**Closed** 2017-10-30 19:40 UTC
Labels: bug, has HS to-notify, Priority: Medium
